import { Nation, User } from '../types';

/**
 * 临时基础前端展示数据 (Demo / Showcase Data)
 * 供用户快速测试投降机制、外交系统、军事与经济看板
 * 后续可一键完整清除或删除本文件
 */

export const DEMO_SHOWCASE_USERS: User[] = [
 {
  id: 'demo_user_solaria',
  username: '统帅·索拉里斯',
  douyinName: '日光帝国官方',
  role: 'user',
  avatarColor: '#f59e0b',
  createdAt: new Date().toISOString(),
 },
 {
  id: 'demo_user_valoria',
  username: '大公·瓦洛里亚',
  douyinName: '瓦洛里亚国防部',
  role: 'user',
  avatarColor: '#3b82f6',
  createdAt: new Date().toISOString(),
 },
 {
  id: 'demo_user_kragor',
  username: '铁血执政官·克拉格',
  douyinName: '克拉格要塞广播',
  role: 'user',
  avatarColor: '#ef4444',
  createdAt: new Date().toISOString(),
 },
 {
  id: 'demo_user_elysia',
  username: '议会长·爱丽西亚',
  douyinName: '爱丽西亚商会',
  role: 'user',
  avatarColor: '#10b981',
  createdAt: new Date().toISOString(),
 },
];

export const DEMO_SHOWCASE_NATIONS: Nation[] = [
 {
  id: 'demo_nat_solaria',
  ownerId: 'demo_user_solaria',
  ownerUsername: '统帅·索拉里斯',
  ownerDouyinName: '日光帝国官方',
  name: '索拉利亚帝国',
  capital: '日光主城 (Helios)',
  territory: '包含东部丘陵走廊与中央平原',
  description: '历史悠久的阳光帝国，工业发达，民生富庶。但近期边境爆发局部武装摩擦。',
  regime: '君主立宪制',
  ideology: '中立和平主义',
  language: '通用日耳曼语族',
  currency: '日光金镑 (SOL)',
  currencySymbol: '',
  currencyRate: 1.0,
  taxRate: 15,
  flagColor: '#d97706',
  emblemIcon: 'Crown',
  mapCoordinates: [35.5, 102.3],
  createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  updatedAt: new Date().toISOString(),
  stabilityIndex: 85,
  popularApproval: 82,
  surrenderProgress: 12,
  warSupport: 88,
  militaryStrength: 95,
  isCapitulated: false,
  provinces: [
   {
    id: 'prov_sol_1',
    name: '日光主都 (首都)',
    civilianFactories: 12,
    militaryFactories: 8,
    detailedBuildings: {
     civilian_factory: 12,
     military_factory: 8,
     synthetic_refinery: 4,
     radar_station: 2,
     air_base: 3,
     fortress: 4,
     infrastructure: 5,
    },
   },
   {
    id: 'prov_sol_2',
    name: '东部重工走廊',
    civilianFactories: 8,
    militaryFactories: 6,
    detailedBuildings: {
     civilian_factory: 8,
     military_factory: 6,
     synthetic_refinery: 2,
     radar_station: 1,
     air_base: 2,
     fortress: 2,
     infrastructure: 4,
    },
   },
   {
    id: 'prov_sol_3',
    name: '南境平原农港',
    civilianFactories: 5,
    militaryFactories: 2,
    detailedBuildings: {
     civilian_factory: 5,
     military_factory: 2,
     synthetic_refinery: 1,
     radar_station: 1,
     air_base: 1,
     fortress: 1,
     infrastructure: 3,
    },
   },
  ],
  militaryIndustry: {
   productionLines: [
    {
     id: 'line_sol_1',
     equipmentId: 'infantry_1',
     equipmentName: '制式步兵步枪',
     category: 'infantry',
     unitCost: 0.1,
     unitCostDisplay: '0.1 IC/把',
     assignedFactories: 4,
     dailyCapacity: 2000,
     dailyOutput: 20000,
    },
    {
     id: 'line_sol_2',
     equipmentId: 'tank_1',
     equipmentName: '日轮-I型中型坦克',
     category: 'armor',
     unitCost: 20,
     unitCostDisplay: '20 IC/辆',
     assignedFactories: 4,
     dailyCapacity: 2000,
     dailyOutput: 100,
    },
   ],
   customDesigns: [],
   stockpiles: {
    infantry_weapons: 25000,
    support_equipment: 4800,
    tanks: 320,
    artillery: 850,
    fighters: 180,
   },
  },
  activeWars: [],
  activeTreaties: [],
 },
 {
  id: 'demo_nat_valoria',
  ownerId: 'demo_user_valoria',
  ownerUsername: '大公·瓦洛里亚',
  ownerDouyinName: '瓦洛里亚国防部',
  name: '瓦洛里亚联邦共和国',
  capital: '瓦伦堡 (Valen)',
  territory: '地处西北峡湾与沿海贸易港',
  description: '推崇自由贸易与科技革新的海洋联邦，拥有先进的航空与雷达预警体系。',
  regime: '联邦共和制',
  ideology: '自由民主主义',
  language: '瓦洛尼亚拉丁语',
  currency: '瓦伦信用银币 (VAL)',
  currencySymbol: '',
  currencyRate: 1.25,
  taxRate: 18,
  flagColor: '#2563eb',
  emblemIcon: 'Shield',
  mapCoordinates: [48.2, 85.1],
  createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  updatedAt: new Date().toISOString(),
  stabilityIndex: 78,
  popularApproval: 75,
  surrenderProgress: 28,
  warSupport: 68,
  militaryStrength: 82,
  isCapitulated: false,
  occupiedProvinces: ['外围哨戒群岛'],
  recentDefeats: 4,
  provinces: [
   {
    id: 'prov_val_1',
    name: '瓦伦堡首府',
    civilianFactories: 10,
    militaryFactories: 6,
    detailedBuildings: {
     civilian_factory: 10,
     military_factory: 6,
     synthetic_refinery: 3,
     radar_station: 3,
     air_base: 4,
     fortress: 3,
     infrastructure: 5,
    },
   },
   {
    id: 'prov_val_2',
    name: '新海港湾造船行省',
    civilianFactories: 6,
    militaryFactories: 4,
    detailedBuildings: {
     civilian_factory: 6,
     military_factory: 4,
     synthetic_refinery: 2,
     naval_dockyard: 4,
     radar_station: 2,
     air_base: 2,
     fortress: 2,
     infrastructure: 4,
    },
   },
  ],
  militaryIndustry: {
   productionLines: [
    {
     id: 'line_val_1',
     equipmentId: 'fighter_1',
     equipmentName: '海燕战术截击机',
     category: 'designer',
     unitCost: 15,
     unitCostDisplay: '15 IC/架',
     assignedFactories: 4,
     dailyCapacity: 2000,
     dailyOutput: 133,
    },
   ],
   customDesigns: [],
   stockpiles: {
    infantry_weapons: 18000,
    support_equipment: 3200,
    tanks: 190,
    artillery: 420,
    fighters: 240,
   },
  },
  activeWars: [],
  activeTreaties: [],
 },
 {
  id: 'demo_nat_kragor',
  ownerId: 'demo_user_kragor',
  ownerUsername: '铁血执政官·克拉格',
  ownerDouyinName: '克拉格要塞广播',
  name: '克拉格军政要塞国',
  capital: '钢铁巨岩城 (Krag-Fortress)',
  territory: '扼守黑石山脉与北部峡谷通道',
  description: '高度军事化要塞国家，前线连战受挫，重工业受损，正面临严重的投降与溃败危机！',
  regime: '军政府/军国主义',
  ideology: '扩张威权主义',
  language: '黑石军令语',
  currency: '克拉格铸铁战券 (KRG)',
  currencySymbol: '',
  currencyRate: 0.75,
  taxRate: 30,
  flagColor: '#dc2626',
  emblemIcon: 'Swords',
  mapCoordinates: [55.1, 115.4],
  createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  updatedAt: new Date().toISOString(),
  stabilityIndex: 32,
  popularApproval: 25,
  surrenderProgress: 72,
  warSupport: 22,
  militaryStrength: 35,
  isCapitulated: false,
  occupiedProvinces: ['黑石北境矿区', '前哨外围要塞群'],
  recentDefeats: 18,
  provinces: [
   {
    id: 'prov_kra_1',
    name: '钢铁巨岩要塞 (首都)',
    civilianFactories: 3,
    militaryFactories: 7,
    detailedBuildings: {
     civilian_factory: 3,
     military_factory: 7,
     synthetic_refinery: 1,
     radar_station: 1,
     air_base: 2,
     fortress: 5,
     infrastructure: 3,
    },
   },
   {
    id: 'prov_kra_2',
    name: '黑石北境矿区 (已沦陷)',
    civilianFactories: 1,
    militaryFactories: 2,
    detailedBuildings: {
     civilian_factory: 1,
     military_factory: 2,
     synthetic_refinery: 0,
     radar_station: 0,
     air_base: 1,
     fortress: 1,
     infrastructure: 1,
    },
   },
  ],
  militaryIndustry: {
   productionLines: [],
   customDesigns: [],
   stockpiles: {
    infantry_weapons: 6000,
    support_equipment: 900,
    tanks: 65,
    artillery: 180,
    fighters: 30,
   },
  },
  activeWars: [
   {
    withNationId: 'demo_nat_solaria',
    withNationName: '索拉利亚帝国',
    initiatedByMe: true,
    since: new Date(Date.now() - 86400000 * 2).toISOString(),
    warGoal: '黑石走廊领土争议',
    disputeProvinceName: '黑石走廊',
   },
  ],
  activeTreaties: [],
 },
 {
  id: 'demo_nat_elysia',
  ownerId: 'demo_user_elysia',
  ownerUsername: '议会长·爱丽西亚',
  ownerDouyinName: '爱丽西亚商会',
  name: '爱丽西亚自由城邦联盟',
  capital: '翡翠港湾 (Emerald Bay)',
  territory: '南部群岛与商业自由港口',
  description: '富庶的商业城邦，金融网络遍布全大陆，拥有强大的外汇储备与造船民用产能。',
  regime: '自由城邦自治',
  ideology: '重商资本主义',
  language: '爱丽西亚商业公语',
  currency: '翡翠金币 (EMR)',
  currencySymbol: '',
  currencyRate: 1.5,
  taxRate: 10,
  flagColor: '#059669',
  emblemIcon: 'Coins',
  mapCoordinates: [22.8, 110.2],
  createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  updatedAt: new Date().toISOString(),
  stabilityIndex: 92,
  popularApproval: 88,
  surrenderProgress: 4,
  warSupport: 92,
  militaryStrength: 90,
  isCapitulated: false,
  provinces: [
   {
    id: 'prov_ely_1',
    name: '翡翠港湾首府',
    civilianFactories: 16,
    militaryFactories: 3,
    detailedBuildings: {
     civilian_factory: 16,
     military_factory: 3,
     synthetic_refinery: 5,
     naval_dockyard: 5,
     radar_station: 2,
     air_base: 2,
     fortress: 2,
     infrastructure: 5,
    },
   },
  ],
  militaryIndustry: {
   productionLines: [],
   customDesigns: [],
   stockpiles: {
    infantry_weapons: 12000,
    support_equipment: 2100,
    tanks: 80,
    artillery: 260,
    fighters: 110,
   },
  },
  activeWars: [],
  activeTreaties: [],
 },
];
