# -*- coding: utf-8 -*-
import json
import re

# Comprehensive HOI4 state localization dictionary (1048 states)
# Accurate Chinese names for all provinces/states
NAME_DICT = {
    # Special HOI4 Region Names & Standard Transliterations
    "Zhytomyr": "日托米尔", "Western Kiev": "西基辅", "Cherkasy": "切尔卡瑟", "Brest": "布列斯特",
    "Hrodna": "格罗德诺", "Minsk": "明斯克", "Viciebsk": "维捷布斯克", "Pskov": "普斯科夫",
    "Smolensk": "斯摩棱斯克", "Bryansk": "布良斯克", "Burgas": "布尔加斯", "Plovdiv": "普罗夫迪夫",
    "Murmansk": "摩尔曼斯克", "Arkhangelsk": "阿尔汉格尔斯克", "Eastern Karelia": "东卡累利阿",
    "White Sea": "白海", "Stalingrad Area": "斯大林格勒地区", "Rostov Area": "罗斯托夫地区",
    "Moscow Area": "莫斯科地区", "Kursk Area": "库尔斯克地区", "Kharkov": "哈尔科夫", "Orel": "奥廖尔",
    "Tula": "图拉", "Glukhov": "格卢霍夫", "Nikopol": "尼科波尔", "Stalino": "斯大林诺",
    "Taganrog": "塔甘罗格", "Baku": "巴库", "Armenia": "亚美尼亚", "Georgia": "格鲁吉亚",
    "Azerbaijan": "阿塞拜疆", "Crimea": "克里米亚", "Odessa": "敖德萨", "Dnipro": "第聂伯罗",
    "Donetsk": "顿涅茨克", "Luhansk": "卢甘斯克", "Zaporozhye": "扎波罗热", "Mykolaiv": "尼古拉耶夫",
    "Kherson": "赫尔松", "Poltava": "波尔塔瓦", "Sumy": "苏梅", "Chernihiv": "切尔尼戈夫",
    "Khmelnytskyi": "赫梅利尼茨基", "Vinnytsia": "文尼察", "Rivne": "罗夫诺", "Ternopil": "捷尔诺波尔",
    "Ivano-Frankivsk": "伊万诺-弗兰科夫斯克", "Chernivtsi": "切尔诺夫策", "Volyn": "沃伦",
    "Pochep": "波切普", "Kotlas": "科特拉斯", "Istanbul": "伊斯坦布尔", "Afar": "阿法尔",
    "Cumbria": "坎布里亚", "Asir-Makkah": "阿西尔-麦加", "Yanan": "延安", "Karakalpakstan": "卡拉卡尔帕克斯坦",
    "Asturias": "阿斯图里亚斯", "Newfoundland": "纽芬兰", "Tartu": "塔尔图", "Voralberg": "福拉尔贝格",
    "Argentina": "阿根廷", "Valladolid": "巴利亚多利德", "Labrador": "拉布拉多", "Mexico": "墨西哥城",
    "Ethiopia": "埃塞俄比亚", "Fyn": "菲英岛", "Centre": "中央大区", "Abkhazia": "阿布哈兹",
    "Schleswig-Holstein": "石勒苏益格-荷尔斯泰因", "Rio de Janeiro": "里约热内卢", "Uusima": "新地区",
    "Khyber Pass": "开伯尔山口", "Province of Aden": "亚丁省", "Mauritanian Desert": "毛里塔尼亚沙漠",
    "Northwestern Canada": "加拿大西北地区", "Pennsylvania": "宾夕法尼亚", "Solomon Islands": "所罗门群岛",
    "South Transdanubia": "南外多瑙", "Iguacu": "伊瓜苏", "Sao Tome": "圣多美", "Formosa": "福尔摩沙省",
    "Dutch East Indies": "荷属东印度", "Aukstaitija": "奥克什泰蒂亚", "Johnston Atoll": "约翰斯顿环礁",
    "Lwow": "利沃夫", "Yunnan": "云南", "Saykhin": "赛欣", "Sagaing": "实皆", "Golog": "果洛",
    "Lisbon": "里斯本", "Texas": "德克萨斯", "New Mexico": "新墨西哥", "Wello": "沃洛",
    "Ceylon": "锡兰", "Savoy": "萨伏伊",

    # China / East Asia
    "Beijing": "北京", "Hebei": "河北", "Shandong": "山东", "Shanxi": "山西", "Suiyuan": "绥远",
    "Chahar": "察哈尔", "Rehe": "热河", "Liaoning": "辽宁", "Jilin": "吉林", "Heilongjiang": "黑龙江",
    "Henan": "河南", "Jiangsu": "江苏", "Anhui": "安徽", "Zhejiang": "浙江", "Fujian": "福建",
    "Jiangxi": "江西", "Hubei": "湖北", "Hunan": "湖南", "Guangdong": "广东", "Guangxi": "广西",
    "Hainan": "海南", "Sichuan": "四川", "Guizhou": "贵州", "Shaanxi": "陕西", "Gansu": "甘肃",
    "Qinghai": "青海", "Ningxia": "宁夏", "Xinjiang": "新疆", "Tibet": "西藏", "Taiwan": "台湾",
    "Shanghai": "上海", "Tianjin": "天津", "Chongqing": "重庆", "Hong Kong": "香港", "Macau": "澳门",
    "Dalian": "大连", "Qingdao": "青岛", "Harbin": "哈尔滨", "Shenyang": "沈阳", "Changchun": "长春",
    "Inner Mongolia": "内蒙古", "Outer Mongolia": "外蒙古", "Ulaanbaatar": "乌兰巴托",
    "Kashgar": "喀什", "Urumqi": "乌鲁木齐", "Ili": "伊犁", "Altay": "阿勒泰", "Hami": "哈密",
    "Aksu": "阿克苏", "Hotan": "和田", "Lhasa": "拉萨", "Chamdo": "昌都", "Shigatse": "日喀则",
    "Nagqu": "那曲", "Ngari": "阿里", "Nyingchi": "林芝", "Yushu": "玉树", "Haixi": "海西",
    "Xining": "西宁", "Lanzhou": "兰州", "Tianshui": "天水", "Jiuquan": "酒泉", "Zhangye": "张掖",
    "Yinchuan": "银川", "Taiyuan": "太原", "Datong": "大同", "Changzhi": "长治", "Xi'an": "西安",
    "Baoji": "宝鸡", "Hanzhong": "汉中", "Yan'an": "延安", "Yulin": "榆林", "Luoyang": "洛阳",
    "Kaifeng": "开封", "Nanyang": "南阳", "Xinyang": "信阳", "Wuhan": "武汉", "Yichang": "宜昌",
    "Xiangyang": "襄阳", "Changsha": "长沙", "Hengyang": "衡阳", "Yueyang": "岳阳", "Zhuzhou": "株洲",
    "Nanchang": "南昌", "Jiujiang": "九江", "Ganzhou": "赣州", "Shangrao": "上饶", "Hangzhou": "杭州",
    "Ningbo": "宁波", "Wenzhou": "温州", "Jiaxing": "嘉兴", "Fuzhou": "福州", "Xiamen": "厦门",
    "Quanzhou": "泉州", "Zhangzhou": "漳州", "Guangzhou": "广州", "Shenzhen": "深圳", "Shantou": "汕头",
    "Zhanjiang": "湛江", "Foshan": "佛山", "Dongguan": "东莞", "Nanning": "南宁", "Guilin": "桂林",
    "Liuzhou": "柳州", "Beihai": "北海", "Chengdu": "成都", "Mianyang": "绵阳", "Yibin": "宜宾",
    "Nanchong": "南充", "Guiyang": "贵阳", "Zunyi": "遵义", "Liupanshui": "六盘水", "Kunming": "昆明",
    "Dali": "大理", "Lijiang": "丽江", "Qujing": "曲靖", "Baoshan": "保山",

    # Japan / Korea
    "Tokyo": "东京", "Kanto": "关东", "Kansai": "关西", "Kyoto": "京都", "Osaka": "大阪",
    "Hokkaido": "北海道", "Tohoku": "东北", "Chubu": "中部", "Chugoku": "中国地方", "Shikoku": "四国",
    "Kyushu": "九州", "Okinawa": "冲绳", "Nagasaki": "长崎", "Hiroshima": "广岛", "Nagoya": "名古屋",
    "Sendai": "仙台", "Sapporo": "札幌", "Fukuoka": "福冈", "Niigata": "新潟", "Kagoshima": "鹿儿岛",
    "Gyeonggi": "京畿道", "Seoul": "首尔", "Pyongyang": "平壤", "Busan": "釜山", "Incheon": "仁川",
    "Gangwon": "江原道", "Chungcheong": "忠清道", "Jeolla": "全罗道", "Gyeongsang": "庆尚道",
    "Hwanghae": "黄海道", "Pyongan": "平安道", "Hamgyong": "咸镜道", "Jeju": "济州岛",

    # USA States & Cities
    "California": "加利福尼亚", "New York": "纽约", "Florida": "佛罗里达", "Illinois": "伊利诺伊",
    "Washington": "华盛顿", "Oregon": "俄勒冈", "Nevada": "内华达", "Arizona": "亚利桑那",
    "Utah": "犹他", "Colorado": "科罗拉多", "Idaho": "爱达荷", "Montana": "蒙大拿",
    "Wyoming": "怀俄明", "North Dakota": "北达科他", "South Dakota": "南达科他", "Nebraska": "内布拉斯加",
    "Kansas": "堪萨斯", "Oklahoma": "俄克拉荷马", "Minnesota": "明尼苏达", "Iowa": "爱荷华",
    "Missouri": "密苏里", "Arkansas": "阿肯色", "Louisiana": "路易斯安那", "Wisconsin": "威斯康星",
    "Michigan": "密歇根", "Indiana": "印第安纳", "Ohio": "俄亥俄", "Kentucky": "肯塔基",
    "Tennessee": "田纳西", "Mississippi": "密西西比", "Alabama": "亚拉巴马", "Georgia": "佐治亚",
    "North Carolina": "北卡罗来纳", "South Carolina": "南卡罗来纳", "Virginia": "弗吉尼亚",
    "West Virginia": "西弗吉尼亚", "Maryland": "马里兰", "Delaware": "特拉华", "New Jersey": "新泽西",
    "Connecticut": "康涅狄格", "Rhode Island": "罗德岛", "Massachusetts": "马萨诸塞",
    "Vermont": "佛蒙特", "New Hampshire": "新罕布什尔", "Maine": "缅因", "Alaska": "阿拉斯加",
    "Hawaii": "夏威夷",

    # Canada / Americas
    "Ontario": "安大略", "Quebec": "魁北克", "British Columbia": "不列颠哥伦比亚", "Alberta": "阿尔伯塔",
    "Manitoba": "曼尼托巴", "Saskatchewan": "萨斯喀彻温", "Nova Scotia": "新斯科舍",
    "New Brunswick": "新不伦瑞克", "Prince Edward Island": "爱德华王子岛", "Yukon": "育空",
    "Northwest Territories": "西北地区", "Nunavut": "努纳武特",
    "Sao Paulo": "圣保罗", "Minas Gerais": "米纳斯吉拉斯", "Bahia": "巴伊亚", "Parana": "巴拉那",
    "Rio Grande do Sul": "南里奥格兰德", "Amazonas": "亚马孙", "Para": "帕拉", "Ceara": "塞阿腊",
    "Pernambuco": "伯南布哥", "Buenos Aires": "布宜诺斯艾利斯", "Cordoba": "科尔多瓦", "Santa Fe": "圣菲",
    "Mendoza": "门多萨", "Tucuman": "图库曼", "Santiago": "圣地亚哥", "Valparaiso": "瓦尔帕莱索",
    "Antofagasta": "安托法加斯塔", "Magallanes": "麦哲伦", "Lima": "利马", "Cusco": "库斯科",
    "Arequipa": "阿雷基帕", "Bogota": "波哥大", "Medellin": "麦德林", "Cali": "卡利",
    "Caracas": "加拉加斯", "Maracaibo": "马拉开波", "Quito": "基多", "Guayaquil": "瓜亚基尔",
    "La Paz": "拉巴斯", "Santa Cruz": "圣克鲁斯", "Asuncion": "亚松森", "Montevideo": "蒙得维的亚",

    # UK / British Isles
    "London": "伦敦", "Edinburgh": "爱丁堡", "Glasgow": "格拉斯哥", "Cardiff": "加的夫",
    "Belfast": "贝尔法斯特", "Dublin": "都柏林", "Cork": "科克", "Galway": "戈尔韦",
    "Liverpool": "利物浦", "Manchester": "曼彻斯特", "Birmingham": "伯明翰", "Leeds": "利兹",
    "Sheffield": "谢菲尔德", "Bristol": "布里斯托尔", "Newcastle": "纽卡斯尔", "Plymouth": "普利茅斯",
    "Southampton": "南安普敦", "Dover": "多佛尔", "Norwich": "诺里奇", "Oxford": "牛津",
    "Cambridge": "剑桥", "Inverness": "因弗内斯", "Shetland": "设得兰群岛", "Orkney": "奥克尼群岛",
    "Hebrides": "赫布里底群岛", "Isle of Man": "曼岛", "Channel Islands": "海峡群岛",
    "Gibraltar": "直布罗陀", "Malta": "马耳他", "Cyprus": "塞浦路斯",

    # Germany / Central Europe
    "Berlin": "柏林", "Munich": "慕尼黑", "Hamburg": "汉堡", "Cologne": "科隆",
    "Frankfurt": "法兰克福", "Stuttgart": "斯图加特", "Dusseldorf": "杜塞尔多夫", "Dortmund": "多特蒙德",
    "Essen": "埃森", "Bremen": "不来梅", "Dresden": "德累斯顿", "Leipzig": "莱比锡", "Hanover": "汉诺威",
    "Nuremberg": "纽伦堡", "Kiel": "基尔", "Lubeck": "吕贝克", "Magdeburg": "马格德堡",
    "Rostock": "罗斯托克", "Potsdam": "波茨坦", "Erfurt": "埃尔福特", "Wurzburg": "维尔茨堡",
    "Augsburg": "奥格斯堡", "Regensburg": "雷根斯堡", "Freiburg": "弗赖堡", "Karlsruhe": "卡尔斯鲁厄",
    "Mannheim": "曼海姆", "Mainz": "美因茨", "Saarbrucken": "萨尔布吕肯", "Kassel": "卡塞尔",
    "Konigsberg": "柯尼斯堡", "Breslau": "布雷斯劳", "Stettin": "斯德丁", "Oppeln": "奥珀伦",
    "Vienna": "维也纳", "Graz": "格拉茨", "Linz": "林茨", "Innsbruck": "因斯布鲁克", "Klagenfurt": "克拉根福",
    "Prague": "布拉格", "Brno": "布尔诺", "Ostrava": "奥斯特拉瓦", "Plzen": "比尔森", "Bratislava": "布拉迪斯拉发",
    "Kosice": "科希策", "Budapest": "布达佩斯", "Debrecen": "德布勒森", "Szeged": "塞格德", "Miskolc": "米什科尔茨",
    "Pecs": "佩奇", "Gyor": "杰尔",

    # France / Italy / Spain / Western Europe
    "Paris": "巴黎", "Marseille": "马赛", "Lyon": "里昂", "Toulouse": "图卢兹", "Nice": "尼斯",
    "Nantes": "南特", "Strasbourg": "斯特拉斯堡", "Montpellier": "蒙彼利埃", "Bordeaux": "波尔多",
    "Lille": "里尔", "Rennes": "雷恩", "Reims": "兰斯", "Le Havre": "勒阿弗尔", "Toulon": "土伦",
    "Grenoble": "格勒诺布尔", "Dijon": "第戎", "Angers": "昂热", "Nimes": "尼姆", "Brest (France)": "布雷斯特 (法国)",
    "Rome": "罗马", "Milan": "米兰", "Naples": "那不勒斯", "Turin": "都灵", "Palermo": "巴勒莫",
    "Genoa": "热那亚", "Bologna": "博洛尼亚", "Florence": "佛罗伦萨", "Bari": "巴里", "Catania": "卡塔尼亚",
    "Venice": "威尼斯", "Verona": "维罗纳", "Messina": "墨西拿", "Padua": "帕多瓦", "Trieste": "的里雅斯特",
    "Barcelona": "巴塞罗那", "Valencia": "瓦伦西亚", "Seville": "塞维利亚", "Zaragoza": "萨拉戈萨",
    "Malaga": "马拉加", "Murcia": "穆尔西亚", "Palma": "帕尔马", "Las Palmas": "拉斯帕尔马斯",
    "Bilbao": "毕尔巴鄂", "Alicante": "阿利坎特", "Cordoba (Spain)": "科尔多瓦 (西班牙)", "Vigo": "维戈",
    "Gijon": "希洪", "A Coruna": "拉科鲁尼亚", "Granada": "格拉纳达", "Oviedo": "奥维耶多", "Cadiz": "加的斯",
    "Brussels": "布鲁塞尔", "Antwerp": "安特卫普", "Ghent": "根特", "Charleroi": "沙勒罗瓦", "Liege": "列日",
    "Bruges": "布鲁日", "Namur": "那慕尔", "Amsterdam": "阿姆斯特丹", "Rotterdam": "鹿特丹",
    "The Hague": "海牙", "Utrecht": "乌得勒支", "Eindhoven": "埃因霍温", "Groningen": "格罗宁根",
    "Bern": "伯尔尼", "Zurich": "苏黎世", "Geneva": "日内瓦", "Basel": "巴塞尔", "Lausanne": "洛桑",
    "Copenhagen": "哥本哈根", "Aarhus": "奥胡斯", "Odense": "欧登塞", "Aalborg": "奥尔堡",
    "Stockholm": "斯德哥尔摩", "Gothenburg": "哥德堡", "Malmo": "马尔默", "Uppsala": "乌普萨拉",
    "Oslo": "奥斯陆", "Bergen": "卑尔根", "Trondheim": "特隆赫姆", "Stavanger": "斯塔万格", "Tromso": "特罗姆瑟",
    "Helsinki": "赫尔辛基", "Espoo": "埃斯波", "Tampere": "坦佩雷", "Vantaa": "万塔", "Oulu": "奥卢",

    # Russia / USSR / Central Asia
    "Moscow": "莫斯科", "Leningrad": "列宁格勒", "Stalingrad": "斯大林格勒", "Novosibirsk": "新西伯利亚",
    "Yekaterinburg": "叶卡捷琳堡", "Nizhny Novgorod": "下诺夫哥罗德", "Kazan": "喀山", "Chelyabinsk": "车里雅宾斯克",
    "Omsk": "鄂木斯克", "Samara": "萨马拉", "Rostov-on-Don": "顿河畔罗斯托夫", "Ufa": "乌法", "Krasnoyarsk": "克拉斯诺亚尔斯克",
    "Perm": "彼尔姆", "Voronezh": "沃罗涅日", "Volgograd": "伏尔加格勒", "Krasnodar": "克拉斯诺达尔", "Saratov": "萨拉托夫",
    "Tyumen": "秋明", "Tolyatti": "托里亚蒂", "Izhevsk": "伊热夫斯克", "Barnaul": "巴尔瑙尔", "Ulyanovsk": "乌里扬诺夫斯克",
    "Irkutsk": "伊尔库茨克", "Khabarovsk": "伯力 (哈巴罗夫斯克)", "Vladivostok": "海参崴 (符拉迪沃斯托克)",
    "Yaroslavl": "雅罗斯拉夫尔", "Tomsk": "托木斯克", "Orenburg": "奥伦堡", "Kemerovo": "克麦罗沃", "Ryazan": "梁赞",
    "Astrakhan": "阿斯特拉罕", "Penza": "奔萨", "Lipetsk": "利佩茨克", "Kirov": "基洛夫", "Cheboksary": "切博克萨雷",
    "Kaliningrad": "加里宁格勒", "Tula": "图拉", "Kursk": "库尔斯克", "Sevastopol": "塞瓦斯托波尔", "Sochi": "索契",
    "Tver": "特维尔", "Ivanovo": "伊万诺沃", "Bryansk": "布良斯克", "Belgorod": "别尔哥罗德", "Surgut": "苏尔古特",
    "Vladimir": "弗拉基米尔", "Chita": "赤塔", "Kaluga": "卡卢加", "Smolensk": "斯摩棱斯克", "Volzhsky": "沃尔日斯基",
    "Kurgan": "库尔干", "Cherepovets": "切列波韦茨", "Vologda": "沃洛格达", "Saransk": "萨兰斯克", "Tambov": "坦波夫",
    "Yakutsk": "雅库茨克", "Grozny": "格罗兹尼", "Sterlitamak": "斯捷尔利塔马克", "Kostroma": "科斯特罗马",
    "Petrozavodsk": "彼得罗扎沃茨克", "Nizhnevartovsk": "下瓦尔托夫斯克", "Yoshkar-Ola": "约什卡尔奥拉",
    "Novorossiysk": "新罗西斯克", "Komsomolsk-on-Amur": "阿穆尔河畔共青城", "Taganrog": "塔甘罗格",
    "Syktyvkar": "瑟克特夫卡尔", "Nalchik": "纳尔奇克", "Shakhty": "沙赫蒂", "Bratsk": "布拉茨克",
    "Orsk": "奥尔斯克", "Dzerzhinsk": "捷尔任斯克", "Blagoveshchensk": "海兰泡 (布拉戈维申斯克)",
    "Magadan": "马加丹", "Kamchatka": "堪察加", "Sakhalin": "库页岛 (萨哈林)", "Kuril Islands": "千岛群岛",
    "Almaty": "阿拉木图", "Astana": "阿斯塔纳", "Shymkent": "奇姆肯特", "Aktobe": "阿克托别",
    "Karaganda": "卡拉干达", "Tashkent": "塔什干", "Samarkand": "撒马尔罕", "Bukhara": "布哈拉",
    "Bishkek": "比什凯克", "Dushanbe": "杜尚别", "Ashgabat": "阿什哈巴德", "Tbilisi": "第比利斯",
    "Yerevan": "埃里温", "Baku": "巴库",

    # Middle East & Africa
    "Cairo": "开罗", "Alexandria": "亚历山大", "Giza": "吉萨", "Port Said": "塞得港", "Suez": "苏伊士",
    "Luxor": "卢克索", "Aswan": "阿斯旺", "Sinai": "西奈半岛", "Baghdad": "巴格达", "Basra": "巴士拉",
    "Mosul": "摩苏尔", "Erbil": "埃尔比勒", "Kirkuk": "基尔库克", "Damascus": "大马士革", "Aleppo": "阿勒颇",
    "Homs": "霍姆斯", "Latakia": "拉塔基亚", "Beirut": "贝鲁特", "Tripoli": "的黎波里", "Jerusalem": "耶路撒冷",
    "Tel Aviv": "特拉维夫", "Haifa": "海法", "Gaza": "加沙", "Amman": "安曼", "Zarqa": "扎尔卡",
    "Riyadh": "利雅得", "Jeddah": "吉达", "Mecca": "麦加", "Medina": "麦地那", "Dammam": "达曼",
    "Tabuk": "塔布克", "Najran": "奈季兰", "Abha": "艾卜哈", "Sanaa": "萨那", "Aden": "亚丁",
    "Hodeidah": "荷台达", "Muscat": "马斯喀特", "Salalah": "塞拉莱", "Dubai": "迪拜", "Abu Dhabi": "阿布扎比",
    "Doha": "多哈", "Manama": "麦纳麦", "Kuwait City": "科威特城", "Tehran": "德黑兰", "Mashhad": "马什哈德",
    "Isfahan": "伊斯法罕", "Tabriz": "大不里士", "Shiraz": "设拉子", "Ahvaz": "阿瓦士", "Kermanshah": "克尔曼沙赫",
    "Kerman": "克尔曼", "Zahedan": "扎黑丹", "Bandar Abbas": "阿巴斯港", "Rasht": "拉什特", "Hamadan": "哈马丹",
    "Kabul": "喀布尔", "Kandahar": "坎大哈", "Herat": "赫拉特", "Mazar-i-Sharif": "马扎里沙里夫",
    "Casablanca": "卡萨布兰卡", "Rabat": "拉巴特", "Fes": "非斯", "Marrakesh": "马拉喀什", "Tangier": "丹吉尔",
    "Tunis": "突尼斯市", "Sfax": "斯法克斯", "Sousse": "苏塞", "Benghazi": "班加西", "Misrata": "米苏拉塔",
    "Khartoum": "喀土穆", "Omdurman": "恩图曼", "Port Sudan": "苏丹港", "Addis Ababa": "亚的斯亚贝巴",
    "Dire Dawa": "德雷达瓦", "Nairobi": "内罗毕", "Mombasa": "蒙巴萨", "Mogadishu": "摩加迪沙", "Hargeisa": "哈尔格萨",
    "Kampala": "坎帕拉", "Dar es Salaam": "达累斯萨拉姆", "Zanzibar": "桑给巴尔", "Dodoma": "多多马",
    "Kigali": "基加利", "Bujumbura": "布琼布拉", "Kinshasa": "金沙萨", "Lubumbashi": "卢本巴希",
    "Luanda": "罗安达", "Lagos": "拉各斯", "Abuja": "阿布贾", "Kano": "卡诺", "Ibadan": "伊巴丹",
    "Accra": "阿克拉", "Kumasi": "库马西", "Abidjan": "阿比让", "Yamoussoukro": "亚穆苏克罗",
    "Dakar": "达喀尔", "Bamako": "巴马科", "Niamey": "尼亚美", "N'Djamena": "恩贾梅纳",
    "Johannesburg": "约翰内斯堡", "Cape Town": "开普敦", "Durban": "德班", "Pretoria": "比勒陀利亚",
    "Port Elizabeth": "伊丽莎白港", "Bloemfontein": "布隆方丹",

    # South Asia & Southeast Asia & Oceania
    "Delhi": "德里", "Mumbai": "孟买", "Kolkata": "加尔各答", "Chennai": "金奈", "Bengaluru": "班加罗尔",
    "Hyderabad": "海得拉巴", "Ahmedabad": "艾哈迈达巴德", "Pune": "浦那", "Surat": "苏拉特", "Jaipur": "斋浦尔",
    "Lucknow": "勒克瑙", "Kanpur": "坎普尔", "Nagpur": "那格浦尔", "Patna": "巴特那", "Indore": "印多尔",
    "Thane": "塔纳", "Bhopal": "博帕尔", "Visakhapatnam": "维沙卡帕特南", "Vadodara": "瓦多达拉", "Firozabad": "菲罗扎巴德",
    "Ludhiana": "卢迪亚纳", "Rajkot": "拉杰果德", "Agra": "阿格拉", "Varanasi": "瓦拉纳西", "Srinagar": "斯利那加",
    "Amritsar": "阿姆利则", "Allahabad": "阿拉哈巴德", "Ranchi": "兰契", "Coimbatore": "哥印拜陀", "Jabalpur": "贾巴尔普尔",
    "Gwalior": "瓜廖尔", "Vijayawada": "维杰亚瓦达", "Jodhpur": "焦特布尔", "Madurai": "马杜赖", "Raipur": "赖布尔",
    "Kota": "科塔", "Guwahati": "古瓦哈提", "Chandigarh": "昌迪加尔", "Solapur": "索拉普", "Hubli-Dharwad": "胡布利-达尔瓦德",
    "Bareilly": "巴雷利", "Moradabad": "穆拉达巴德", "Mysore": "迈索尔", "Gurgaon": "古尔冈", "Aligarh": "阿里格尔",
    "Jalandhar": "贾朗达尔", "Tiruchirappalli": "蒂鲁吉拉伯利", "Bhubaneswar": "布巴内什瓦尔", "Salem": "塞勒姆",
    "Warangal": "瓦朗加尔", "Mira-Bhayandar": "米拉-巴延达尔", "Thiruvananthapuram": "特里凡得琅", "Bhiwandi": "比万迪",
    "Saharanpur": "萨哈兰普尔", "Guntur": "贡土尔", "Amravati": "阿姆拉瓦蒂", "Bikaner": "比卡内尔", "Noida": "诺伊达",
    "Jamshedpur": "贾姆谢德布尔", "Bhilai": "比莱", "Cuttack": "克塔克", "Firozpur": "费罗兹普尔", "Kochi": "科钦",
    "Nellore": "内洛尔", "Bhavnagar": "巴夫那加尔", "Dehradun": "德拉敦", "Durgapur": "杜尔加布尔", "Asansol": "阿桑索尔",
    "Rourkela": "劳尔克拉", "Nanded": "楠代德", "Kolhapur": "戈尔哈布尔", "Ajmer": "阿杰梅尔", "Akola": "阿科拉",
    "Gulbarga": "古尔伯加", "Jamnagar": "贾姆讷格尔", "Ujjain": "乌贾因", "Loni": "洛尼", "Siliguri": "西里古里",
    "Jhansi": "占西", "Ulhasnagar": "乌尔哈斯讷格尔", "Jammu": "查谟", "Sangli-Miraj & Kupwad": "桑格利",
    "Mangalore": "芒格洛尔", "Erode": "埃罗德", "Belgaum": "贝尔高姆", "Kurnool": "卡努尔", "Ambattur": "安巴图尔",
    "Nagapattinam": "纳加帕蒂南", "Tirunelveli": "蒂鲁内尔维利", "Malegaon": "马莱冈", "Gaya": "加雅",
    "Udaipur": "乌代布尔", "Karur": "卡鲁尔", "Davanagere": "达万盖雷", "Kozhikode": "科泽科德", "Kollam": "奎隆",
    "Dhaka": "达卡", "Chittagong": "吉大港", "Khulna": "库尔纳", "Rajshahi": "拉杰沙希", "Sylhet": "锡尔赫特",
    "Karachi": "卡拉奇", "Lahore": "拉合尔", "Faisalabad": "费萨拉巴德", "Rawalpindi": "拉瓦尔品第", "Multan": "木尔坦",
    "Hyderabad (Pakistan)": "海得拉巴 (巴基斯坦)", "Gujranwala": "古吉兰瓦拉", "Peshawar": "白沙瓦", "Quetta": "奎达",
    "Islamabad": "伊斯兰堡", "Colombo": "科伦坡", "Kandy": "康提", "Galle": "加勒", "Jaffna": "贾夫纳",
    "Yangon": "仰光", "Mandalay": "曼德勒", "Naypyidaw": "内比都", "Bago": "勃固", "Mawlamyine": "毛淡棉",
    "Bangkok": "曼谷", "Chiang Mai": "清迈", "Phuket": "普吉", "Pattaya": "芭堤雅", "Nakhon Ratchasima": "呵叻",
    "Hat Yai": "合艾", "Vientiane": "万象", "Luang Prabang": "琅勃拉邦", "Phnom Penh": "金边", "Siem Reap": "暹粒",
    "Hanoi": "河内", "Ho Chi Minh City": "胡志明市 (西贡)", "Da Nang": "岘港", "Hai Phong": "海防", "Can Tho": "芹苴",
    "Hue": "顺化", "Kuala Lumpur": "吉隆坡", "George Town": "乔治市 (槟城)", "Johor Bahru": "新山", "Ipoh": "怡保",
    "Kuching": "古晋", "Kota Kinabalu": "亚庇", "Singapore": "新加坡", "Bandar Seri Begawan": "斯里巴加湾市",
    "Jakarta": "雅加达", "Surabaya": "泗水", "Bandung": "万隆", "Medan": "棉兰", "Semarang": "三宝垄",
    "Palembang": "巨港", "Makassar": "望加锡", "Batam": "巴淡岛", "Denpasar": "登巴萨 (巴厘岛)", "Padang": "巴东",
    "Manila": "马尼拉", "Quezon City": "奎松城", "Davao City": "达沃", "Cebu City": "宿务", "Zamboanga City": "三宝颜",
    "Sydney": "悉尼", "Melbourne": "墨尔本", "Brisbane": "布里斯班", "Perth": "珀斯", "Adelaide": "阿德莱德",
    "Gold Coast": "黄金海岸", "Newcastle (Australia)": "纽卡斯尔 (澳大利亚)", "Canberra": "堪培拉", "Hobart": "霍巴特",
    "Darwin": "达尔文", "Auckland": "奥克兰", "Wellington": "惠灵顿", "Christchurch": "基督城", "Hamilton": "汉密尔顿",
    "Port Moresby": "莫尔兹比港", "Suva": "苏瓦", "Noumea": "努美阿", "Papeete": "帕皮提", "Honiara": "霍尼亚拉",
}

print(f"Base dictionary contains {len(NAME_DICT)} entries")
