import json
import os

# Comprehensive dictionary mapping HOI4 state IDs or English names to standard Chinese translations
STATE_TRANSLATIONS = {
    # 1 - 100
    1: ("Corsica", "科西嘉"),
    2: ("Latium", "拉齐奥"),
    3: ("Campania", "坎帕尼亚"),
    4: ("Calabria", "卡拉布里亚"),
    5: ("Sicily", "西西里"),
    6: ("Sardinia", "撒丁"),
    7: ("Istria", "伊斯特拉"),
    8: ("Dalmatia", "达尔马提亚"),
    9: ("Dodecanese", "十二群岛"),
    10: ("Eritrea", "厄立特里亚"),
    11: ("Somalia", "索马里"),
    12: ("Libya", "利比亚"),
    13: ("Tripolitania", "的黎波里塔尼亚"),
    14: ("Cyrenaica", "昔兰尼加"),
    15: ("Tuscany", "托斯卡纳"),
    16: ("Emilia Romagna", "艾米利亚-罗马涅"),
    17: ("Abruzzo", "阿布鲁佐"),
    18: ("Apulia", "普利亚"),
    19: ("Basilicata", "巴西利卡塔"),
    20: ("Ile de France", "法兰西岛"),
    21: ("Nord-Pas-de-Calais", "北部-加来海峡"),
    22: ("Picardy", "皮卡第"),
    23: ("Normandy", "诺曼底"),
    24: ("Centre", "中央大区"),
    25: ("Pays de la Loire", "卢瓦尔河谷"),
    26: ("Brittany", "布列塔尼"),
    27: ("Poitou", "普瓦图"),
    28: ("Limousin", "利穆赞"),
    29: ("Aquitaine", "阿基坦"),
    30: ("Midi-Pyrenees", "南部-比利牛斯"),
    31: ("Languedoc", "朗格多克"),
    32: ("Provence", "普罗旺斯"),
    33: ("Rhone", "罗讷"),
    34: ("Auvergne", "奥弗涅"),
    35: ("Burgundy", "勃艮第"),
    36: ("Franche-Comte", "弗朗什-孔泰"),
    37: ("Champagne", "香槟"),
    38: ("Lorraine", "洛林"),
    39: ("Alsace", "阿尔萨斯"),
    40: ("Savoy", "萨伏伊"),
    41: ("Algiers", "阿尔及尔"),
    42: ("Oran", "奥兰"),
    43: ("Constantine", "君士坦丁"),
    44: ("Tunisia", "突尼斯"),
    45: ("Southern Tunisia", "南突尼斯"),
    46: ("Morocco", "摩洛哥"),
    47: ("Eastern Morocco", "东摩洛哥"),
    48: ("Southern Morocco", "南摩洛哥"),
    49: ("Senegal", "塞内加尔"),
    50: ("Brandenburg", "勃兰登堡"),
    51: ("Pomerania", "波美拉尼亚"),
    52: ("East Prussia", "东普鲁士"),
    53: ("Mecklenburg", "梅克伦堡"),
    54: ("Lower Saxony", "下萨克森"),
    55: ("Westphalia", "威斯特法伦"),
    56: ("Rhineland", "莱茵兰"),
    57: ("Hesse", "黑森"),
    58: ("Schleswig-Holstein", "石勒苏益格-荷尔斯泰因"),
    59: ("Bavaria", "巴伐利亚"),
    60: ("Saxony", "萨克森"),
    61: ("Thuringia", "图林根"),
    62: ("Franken", "弗兰肯"),
    63: ("Lower Silesia", "下西里西亚"),
    64: ("Upper Silesia", "上西里西亚"),
    65: ("Baden", "巴登"),
    66: ("Wurttemberg", "符腾堡"),
    67: ("Moselland", "摩泽尔"),
    68: ("Voralberg", "福拉尔贝格"),
    69: ("Tirol", "蒂罗尔"),
    70: ("Salzburg", "萨尔茨堡"),
    71: ("Upper Austria", "上奥地利"),
    72: ("Lower Austria", "下奥地利"),
    73: ("Carinthia", "克恩顿"),
    74: ("Styria", "施泰尔马克"),
    75: ("Burgenland", "布尔根兰"),
    76: ("Memel", "梅梅尔"),
    77: ("Bohemia", "波希米亚"),
    78: ("Moravia", "摩拉维亚"),
    79: ("Sudetenland", "苏台德"),
    80: ("Eastern Sudetenland", "东苏台德"),
    81: ("Western Slovakia", "西斯洛伐克"),
    82: ("Eastern Slovakia", "东斯洛伐克"),
    83: ("Carpathian Ruthenia", "喀尔巴阡鲁塞尼亚"),
    84: ("Zaolzie", "扎奥尔热"),
    85: ("Danzig", "但泽"),
    86: ("Poznan", "波兹南"),
    87: ("Warsaw", "华沙"),
    88: ("Lodz", "罗兹"),
    89: ("Krakow", "克拉科夫"),
    90: ("Lwow", "利沃夫"),
    91: ("Stanislawow", "斯坦尼斯瓦乌夫"),
    92: ("Tarnopol", "捷尔诺波尔"),
    93: ("Wolyn", "沃伦"),
    94: ("Polesie", "波列西耶"),
    95: ("Nowogrodek", "诺沃格鲁代克"),
    96: ("Wilno", "维尔纽斯"),
    97: ("Bialystok", "比亚韦斯托克"),
    98: ("Kielce", "凯尔采"),
    99: ("Lublin", "卢布林"),
    100: ("Western Switzerland", "西瑞士"),

    # 101 - 200
    101: ("Eastern Switzerland", "东瑞士"),
    102: ("Tessin", "提契诺"),
    103: ("Luxembourg", "卢森堡"),
    104: ("Holland", "荷兰"),
    105: ("Brabant", "布拉班特"),
    106: ("Friesland", "弗里斯兰"),
    107: ("Flanders", "佛兰德"),
    108: ("Wallonia", "瓦隆"),
    109: ("Zeeland", "西兰"),
    110: ("Lapland", "拉普兰"),
    111: ("Uusima", "新地区"),
    112: ("Lisbon", "里斯本"),
    113: ("Porto", "波尔图"),
    114: ("Beja", "贝哈"),
    115: ("Algarve", "阿尔加维"),
    116: ("Madeira", "马德拉群岛"),
    117: ("Azores", "亚速尔群岛"),
    118: ("Madrid", "马德里"),
    119: ("Catalonia", "加泰罗尼亚"),
    120: ("Valencia", "瓦伦西亚"),
    121: ("Navarre", "纳瓦拉"),
    122: ("Aragon", "阿拉贡"),
    123: ("Castile", "卡斯蒂利亚"),
    124: ("Extremadura", "埃斯特雷马杜拉"),
    125: ("Andalusia", "安达卢西亚"),
    126: ("Granada", "格拉纳达"),
    127: ("Galicia", "加利西亚"),
    128: ("Leon", "莱昂"),
    129: ("Canary Islands", "加那利群岛"),
    130: ("Greater London Area", "大伦敦"),
    131: ("Sussex", "萨塞克斯"),
    132: ("Kent", "肯特"),
    133: ("East Anglia", "东盎格利亚"),
    134: ("Midlands", "米德兰兹"),
    135: ("Lancashire", "兰开夏"),
    136: ("Yorkshire", "约克郡"),
    137: ("Northumberland", "诺森伯兰"),
    138: ("Wales", "威尔士"),
    139: ("Lothian", "洛锡安"),
    140: ("Highlands", "苏格兰高地"),
    141: ("Aberdeenshire", "阿伯丁郡"),
    142: ("Lanark", "拉纳克"),
    143: ("Northern Ireland", "北爱尔兰"),
    144: ("Munster", "芒斯特"),
    145: ("Leinster", "伦斯特"),
    146: ("Connaught", "康诺特"),
    147: ("Svealand", "斯韦阿兰"),
    148: ("Gotaland", "约塔兰"),
    149: ("Norrland", "诺尔兰"),
    150: ("Vasterbotten", "西博滕"),
    151: ("Gotland", "哥特兰岛"),
    152: ("Oslofjord", "奥斯陆峡湾"),
    153: ("Vestlandet", "西挪威"),
    154: ("Trondelag", "特隆德拉格"),
    155: ("Nord-Norge", "北挪威"),
    156: ("Telemark", "泰勒马克"),
    157: ("Western Ostrobothnia", "西博斯尼亚"),
    158: ("Karjala", "卡累利阿"),
    159: ("Savo", "萨沃"),
    160: ("Turku", "图尔库"),
    161: ("Hameenlinna", "海门林纳"),
    162: ("Petsamo", "佩察莫"),
    163: ("Salla", "萨拉"),
    164: ("Aland", "奥兰群岛"),
    165: ("Pohjois-Suomi", "北芬兰"),
    166: ("Pest", "佩斯"),
    167: ("Borsod", "博尔绍德"),
    168: ("Alfold", "大平原"),
    169: ("Transdanubia", "外多瑙"),
    170: ("Crisana", "克里沙纳"),
    171: ("Northern Transylvania", "北特兰西瓦尼亚"),
    172: ("Southern Transylvania", "南特兰西瓦尼亚"),
    173: ("Banat", "巴纳特"),
    174: ("Oltenia", "奥尔特尼亚"),
    175: ("Muntenia", "蒙特尼亚"),
    176: ("Moldavia", "摩尔达维亚"),
    177: ("Dobrudja", "多布罗加"),
    178: ("Bessarabia", "比萨拉比亚"),
    179: ("Northern Bukovina", "北布科维纳"),
    180: ("Southern Bukovina", "南布科维纳"),
    181: ("Slovenia", "斯洛文尼亚"),
    182: ("Croatia", "克罗地亚"),
    183: ("Bosnia", "波斯尼亚"),
    184: ("Herzegovina", "黑塞哥维那"),
    185: ("Vojvodina", "伏伊伏丁那"),
    186: ("Serbia", "塞尔维亚"),
    187: ("Montenegro", "黑山"),
    188: ("Kosovo", "科索沃"),
    189: ("Macedonia", "马其顿"),
    190: ("Tallinn", "塔林"),
    191: ("Tartu", "塔尔图"),
    192: ("Narva", "纳尔瓦"),
    193: ("Saaremaa", "萨雷马岛"),
    194: ("Riga", "里加"),
    195: ("Kurzeme", "库尔兰"),
    196: ("Zemgale", "泽姆加尔"),
    197: ("Vidzeme", "维泽梅"),
    198: ("Latgale", "拉特加尔"),
    199: ("Kaunas", "考纳斯"),
    200: ("Vilnius", "维尔纽斯"),
}

print(f"Loaded {len(STATE_TRANSLATIONS)} base states")
