import { DEFAULT_ACTIVE_DECREE_IDS, PRESET_DECREES } from '../services/strategicGameplayService';
import { ResearchTechItem, ActiveResearchProject, Nation, TechBranchType } from '../types';

export interface TechBranchMeta {
 id: TechBranchType;
 name: string;
 shortName: string;
 iconName: string;
 color: string;
 accentColor: string;
 description: string;
}

export const TECH_BRANCHES: Record<TechBranchType, TechBranchMeta> = {
 infantry: {
  id: 'infantry',
  name: '步兵装备与编制',
  shortName: '步兵',
  iconName: 'rifle',
  color: '#38bdf8',
  accentColor: 'text-sky-400 border-sky-500/40 bg-sky-950/40',
  description: '单兵步枪、半自动/突击步枪、单兵反坦克、夜视瞄具与摩托/机械化运兵载具',
 },
 support: {
  id: 'support',
  name: '支援装备与工勤',
  shortName: '支援装备',
  iconName: 'support',
  color: '#34d399',
  accentColor: 'text-emerald-400 border-emerald-500/40 bg-emerald-950/40',
  description: '野战工兵破障、战地外科医院、装甲侦察连、战地抢修所与战备辎重调度',
 },
 artillery: {
  id: 'artillery',
  name: '炮兵与火力压制',
  shortName: '炮兵',
  iconName: 'artillery',
  color: '#f97316',
  accentColor: 'text-orange-400 border-orange-500/40 bg-orange-950/40',
  description: '牵引轻重榴弹炮、大口径反坦克加农炮、高射机关炮与多管火箭压制群',
 },
 armor: {
  id: 'armor',
  name: '装甲战车与坦克',
  shortName: '装甲',
  iconName: 'tank',
  color: '#fbbf24',
  accentColor: 'text-amber-400 border-amber-500/40 bg-amber-950/40',
  description: '轻型巡航战车、主力中型突破坦克、重型攻坚坦克与无炮塔坦克歼击车',
 },
 industry: {
  id: 'industry',
  name: '国家工业与产能',
  shortName: '工业',
  iconName: 'factory',
  color: '#a855f7',
  accentColor: 'text-purple-400 border-purple-500/40 bg-purple-950/40',
  description: '高精度母机、集中/分散流水线、重型预制建筑、合成油裂化与装甲特种钢',
 },
 air: {
  id: 'air',
  name: '航空战机与空优',
  shortName: '空军',
  iconName: 'fighter',
  color: '#60a5fa',
  accentColor: 'text-blue-400 border-blue-500/40 bg-blue-950/40',
  description: '全金属空优战斗机、近距离对地支援机(CAS)、战术与重型远程战略轰炸机、喷气战机',
 },
 naval: {
  id: 'naval',
  name: '海军舰艇与远洋',
  shortName: '海军',
  iconName: 'warship',
  color: '#2dd4bf',
  accentColor: 'text-teal-400 border-teal-500/40 bg-teal-950/40',
  description: '远洋破交潜艇、舰队驱逐舰、巡洋舰、超无畏战列舰与全通甲板航空母舰',
 },
 electronics: {
  id: 'electronics',
  name: '电子雷达与工程',
  shortName: '电子',
  iconName: 'electronics',
  color: '#ec4899',
  accentColor: 'text-pink-400 border-pink-500/40 bg-pink-950/40',
  description: '差分计算机、密码破译机、甚高频电台、相控阵雷达网与重核裂变反应堆',
 },
};

export const TECH_BRANCH_KEYS: TechBranchType[] = [
 'infantry',
 'support',
 'artillery',
 'armor',
 'industry',
 'air',
 'naval',
 'electronics',
];

export const ALL_RESEARCH_TECHS: ResearchTechItem[] = [
 // ================= 1. 步兵装备与编制 (INFANTRY) =================
 // Row 0: 枪械武器演进线
 {
  id: 'inf_weapons_0',
  name: '基础制式步枪',
  branch: 'infantry',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'rifle',
  artKey: 'rifle_bolt',
  baseDays: 100,
  summary: '配备全国步兵旋转后拉枪机弹仓步枪与基础单兵装具',
  effects: ['步兵软目标杀伤 +10%', '步兵防御能力 +8%', '单兵装备生产耗时降低 5%'],
  stats: { '软目标杀伤': '+10%', '步兵防御': '+8%', '组织度': '+5' },
  historicalQuote: '哪怕战火弥漫，一支可靠的步枪仍是卫国战士手中最忠诚的伙伴。',
 },
 {
  id: 'inf_weapons_1',
  name: '改进步兵枪械',
  branch: 'infantry',
  tier: 2,
  col: 1,
  row: 0,
  year: 1938,
  icon: 'rifle',
  artKey: 'rifle_bolt',
  prerequisiteIds: ['inf_weapons_0'],
  baseDays: 140,
  summary: '配发一体冲压机匣步枪与班用轻机枪，显著提升班组压制火力',
  effects: ['步兵软目标杀伤 +15%', '步兵突破能力 +10%', '对轻掩体压制 +12%'],
  stats: { '软目标杀伤': '+15%', '步兵突破': '+10%', '对人火力': '+15%' },
  historicalQuote: '通过标准化冲压技术，让前线每一个班组都能获得持续倾泻火力的能力。',
 },
 {
  id: 'inf_weapons_2',
  name: '半自动步枪装备',
  branch: 'infantry',
  tier: 3,
  col: 2,
  row: 0,
  year: 1940,
  icon: 'rifle',
  artKey: 'rifle_semi',
  prerequisiteIds: ['inf_weapons_1'],
  baseDays: 175,
  summary: '全军换装导气式半自动主战步枪与高射速冲锋枪',
  effects: ['步兵软目标杀伤 +20%', '城市作战进攻效能 +15%', '防御射速提升 25%'],
  stats: { '软目标杀伤': '+20%', '城市战加成': '+15%', '硬目标杀伤': '+5%' },
  historicalQuote: '一声清脆的退夹声，宣告着步兵火力密度的跨代飞跃。',
 },
 {
  id: 'inf_weapons_3',
  name: '突击步枪与班机',
  branch: 'infantry',
  tier: 4,
  col: 3,
  row: 0,
  year: 1944,
  icon: 'rifle',
  artKey: 'rifle_assault',
  prerequisiteIds: ['inf_weapons_2'],
  baseDays: 210,
  summary: '配发中间威力弹突击步枪，结合步枪射程与冲锋枪射速',
  effects: ['步兵软目标杀伤 +28%', '步兵全地形适应性 +10%', '夜战与堑壕战 +20%'],
  stats: { '软目标杀伤': '+28%', '突破': '+18%', '战壕攻坚': '+20%' },
  historicalQuote: '现代步兵单兵火力的终极形态，重新定义近距离交火交战规则。',
 },
 {
  id: 'inf_weapons_4',
  name: '现代化特种步枪',
  branch: 'infantry',
  tier: 5,
  col: 4,
  row: 0,
  year: 1945,
  icon: 'rifle',
  artKey: 'rifle_assault',
  prerequisiteIds: ['inf_weapons_3', 'inf_night_optics'],
  baseDays: 240,
  summary: '模块化战术枪族，配备快拆光学瞄具与全地形复合消音装置',
  effects: ['全地形软杀伤 +35%', '全军突破能力 +25%', '战损比大幅改善 +30%'],
  stats: { '软目标杀伤': '+35%', '全天候作战': '+30%', '精锐杀伤': '+25%' },
 },

 // Row 1: 单兵重火力与反装甲单兵
 {
  id: 'inf_smg_squad',
  name: '近距战术冲锋枪',
  branch: 'infantry',
  tier: 1,
  col: 0,
  row: 1,
  year: 1936,
  icon: 'rifle',
  artKey: 'smg',
  baseDays: 95,
  summary: '装备大容量弹鼓高射速冲锋枪，专精城镇战与战壕近身突击',
  effects: ['近战城市攻坚 +15%', '战壕扫荡杀伤 +12%'],
  stats: { '近战杀伤': '+15%', '城镇防御': '+10%' },
 },
 {
  id: 'inf_mg_squad_1',
  name: '通用机枪组编制',
  branch: 'infantry',
  tier: 2,
  col: 1,
  row: 1,
  year: 1938,
  icon: 'rifle',
  artKey: 'mg_squad',
  prerequisiteIds: ['inf_smg_squad'],
  baseDays: 130,
  summary: '采用弹链供弹与快速更换枪管设计，形成连绵不绝的交叉火力网',
  effects: ['防御压制力 +25%', '敌军冲锋突破减速 -30%'],
  stats: { '阵地防御': '+25%', '压制值': '+30%' },
 },
 {
  id: 'inf_at_manpad_1',
  name: '单兵反坦克火箭筒',
  branch: 'infantry',
  tier: 3,
  col: 2,
  row: 1,
  year: 1942,
  icon: 'target',
  artKey: 'manpad_at',
  prerequisiteIds: ['inf_mg_squad_1'],
  baseDays: 165,
  summary: '配发空心聚能装药破甲火箭弹（如巴祖卡/铁拳），使步兵具备近距毁坦能力',
  effects: ['步兵硬目标杀伤 +35%', '步兵穿甲深度 +25', '城市战反坦克伏击 +40%'],
  stats: { '硬目标杀伤': '+35%', '穿甲深度': '140mm', '反伏击': '+40%' },
 },
 {
  id: 'inf_night_optics',
  name: '主动红外夜视瞄具',
  branch: 'infantry',
  tier: 4,
  col: 3,
  row: 1,
  year: 1944,
  icon: 'eye',
  artKey: 'night_vision',
  prerequisiteIds: ['inf_at_manpad_1'],
  baseDays: 200,
  summary: '单兵配备红外探照灯与荧光物镜，彻底破除夜战迷雾',
  effects: ['夜战战斗力惩罚 -80%', '夜间伏击胜率 +45%'],
  stats: { '夜战效率': '+80%', '先手发现': '+45%' },
 },

 // Row 2: 摩托化与机械化运兵战车
 {
  id: 'inf_motorized',
  name: '摩托化步兵载具',
  branch: 'infantry',
  tier: 1,
  col: 0,
  row: 2,
  year: 1936,
  icon: 'truck',
  artKey: 'logistics_depot',
  baseDays: 120,
  summary: '引入标准化重型越野军用卡车，实现步兵长途快速机动',
  effects: ['陆军大地图行军速度 +50%', '步兵补给运力 +15%', '战略转移耗时 -25%'],
  stats: { '行军速度': '+50%', '补给效率': '+15%', '地形通过率': '+20%' },
  historicalQuote: '车轮滚滚碾过泥泞，速度即是合围敌军的最锋利刺刀。',
 },
 {
  id: 'inf_mechanized_1',
  name: '半履带装甲运兵车',
  branch: 'infantry',
  tier: 2,
  col: 1,
  row: 2,
  year: 1939,
  icon: 'ifv',
  artKey: 'ifv_halftrack',
  prerequisiteIds: ['inf_motorized'],
  baseDays: 160,
  summary: '具备防弹装甲板的半履带步兵运载车，可抵御弹片与轻武器',
  effects: ['机械化步兵装甲厚度 +15', '硬度 +20%', '伴随装甲协同进攻 +15%'],
  stats: { '装甲厚度': '+15', '部队硬度': '+20%', '软杀伤抗性': '+25%' },
 },
 {
  id: 'inf_mechanized_2',
  name: '全履带重步兵战车',
  branch: 'infantry',
  tier: 3,
  col: 2,
  row: 2,
  year: 1942,
  icon: 'ifv',
  artKey: 'ifv_halftrack',
  prerequisiteIds: ['inf_mechanized_1'],
  baseDays: 190,
  summary: '全封闭越野履带步兵战车，装备车载机关炮与重机枪',
  effects: ['机械化师全地形推进力 +25%', '突破能力 +22%', '防御组织度 +15'],
  stats: { '突破': '+22%', '装甲厚度': '+25', '硬目标杀伤': '+12%' },
 },
 {
  id: 'inf_mechanized_3',
  name: '现代步兵战斗车族',
  branch: 'infantry',
  tier: 4,
  col: 3,
  row: 2,
  year: 1944,
  icon: 'ifv',
  artKey: 'ifv_halftrack',
  prerequisiteIds: ['inf_mechanized_2'],
  baseDays: 220,
  summary: '集成反坦克导弹发射轨与双向稳定 20mm 机关炮的重甲步战车',
  effects: ['机械化师装甲硬度 +40%', '伴随坦克突破加成 +30%'],
  stats: { '综合战力': '+35%', '穿甲深度': '60mm', '行进间射击': '+30%' },
 },

 // ================= 2. 支援装备与工勤 (SUPPORT) =================
 // Row 0: 工兵破障与防御工事
 {
  id: 'sup_engineers_1',
  name: '野战工兵装备 I',
  branch: 'support',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'support',
  artKey: 'engineer_shovel',
  baseDays: 95,
  summary: '标配工兵铁锹、刺丝网、爆破筒与简易野战掩体套件',
  effects: ['阵地战壕构筑上限 +5', '跨河进攻惩罚 -20%', '要塞攻坚效能 +10%'],
  stats: { '战壕上限': '+5', '跨河突破': '+20%', '要塞攻击': '+10%' },
 },
 {
  id: 'sup_engineers_2',
  name: '加强工程破障 II',
  branch: 'support',
  tier: 2,
  col: 1,
  row: 0,
  year: 1939,
  icon: 'support',
  artKey: 'engineer_shovel',
  prerequisiteIds: ['sup_engineers_1'],
  baseDays: 135,
  summary: '配发重型喷火器、地雷探测仪与战地舟桥搭设套件',
  effects: ['战壕构筑速度 +30%', '城市与要塞攻击 +25%', '防御状态反击 +15%'],
  stats: { '战壕速度': '+30%', '要塞攻击': '+25%', '城市战攻击': '+20%' },
 },
 {
  id: 'sup_fort_specialist',
  name: '机械化重型工兵营',
  branch: 'support',
  tier: 3,
  col: 2,
  row: 0,
  year: 1942,
  icon: 'support',
  artKey: 'engineer_shovel',
  prerequisiteIds: ['sup_engineers_2'],
  baseDays: 180,
  summary: '配备装甲破障推土机、桥梁架设坦克与重型工程钻机',
  effects: ['全军要塞攻坚效能 +40%', '跨河移动完全无惩罚', '省份防空工事抗轰炸 +20%'],
  stats: { '要塞攻坚': '+40%', '跨河移动': '+100%', '防御装甲': '+10' },
 },

 // Row 1: 侦察与战场先知
 {
  id: 'sup_recon_1',
  name: '骑兵与摩托侦察连',
  branch: 'support',
  tier: 1,
  col: 0,
  row: 1,
  year: 1936,
  icon: 'truck',
  artKey: 'recon_scout',
  baseDays: 90,
  summary: '派出快速摩托侦察组，前出探明敌军防御薄弱环节',
  effects: ['战场侦察战术选择优势 +15%', '大地图视野范围 +25%', '伏击概率 +15%'],
  stats: { '侦察值': '+1.5', '视野范围': '+25%', '移动速度': '+10%' },
 },
 {
  id: 'sup_recon_armored',
  name: '轻装甲轮式侦察车',
  branch: 'support',
  tier: 2,
  col: 1,
  row: 1,
  year: 1939,
  icon: 'ifv',
  artKey: 'recon_scout',
  prerequisiteIds: ['sup_recon_1'],
  baseDays: 135,
  summary: '装备无线电与 20mm 机关炮的 4x4 装甲车，提供移动掩护与精准情报',
  effects: ['师级战术克制反制成功率 +30%', '行军遭遇战先手率 +35%'],
  stats: { '侦察值': '+2.5', '硬度': '+15%', '战术对抗': '+30%' },
 },
 {
  id: 'sup_recon_air',
  name: '航空校射与侦察分队',
  branch: 'support',
  tier: 3,
  col: 2,
  row: 1,
  year: 1942,
  icon: 'eye',
  artKey: 'recon_scout',
  prerequisiteIds: ['sup_recon_armored'],
  baseDays: 175,
  summary: '前线轻型联络机为空地协同提供火炮落点实时修正',
  effects: ['炮兵跨山脊间接射击精度 +40%', '敌军伪装暴露率 +50%'],
  stats: { '火炮校射': '+40%', '战术视野': '+60%' },
 },

 // Row 2: 战地医院与辎重抢修
 {
  id: 'sup_field_hospital_1',
  name: '野战外科医院连',
  branch: 'support',
  tier: 1,
  col: 0,
  row: 2,
  year: 1937,
  icon: 'manpower',
  artKey: 'field_hospital',
  baseDays: 110,
  summary: '在战线后方设立机动战地医院，抢救重伤官兵并重返前线',
  effects: ['战损兵员人力回收 +20%', '师级老兵战斗经验保留率 +30%'],
  stats: { '人力回收': '+20%', '经验保留': '+30%', '士气损耗': '-15%' },
 },
 {
  id: 'sup_maintenance_1',
  name: '战地修械与抢修所',
  branch: 'support',
  tier: 2,
  col: 1,
  row: 2,
  year: 1939,
  icon: 'wrench',
  artKey: 'maintenance_wrench',
  baseDays: 125,
  summary: '设立野战机动吊臂修车所，从战场回收受损坦克与重炮',
  effects: ['装备损耗率降低 25%', '战场俘获敌军装备概率 +20%'],
  stats: { '装备可靠性': '+20%', '战利品回收': '+20%' },
 },
 {
  id: 'sup_logistics_train',
  name: '军级战备物流枢纽',
  branch: 'support',
  tier: 3,
  col: 2,
  row: 2,
  year: 1942,
  icon: 'truck',
  artKey: 'logistics_depot',
  prerequisiteIds: ['sup_maintenance_1'],
  baseDays: 175,
  summary: '建立标准铁路集装转运站与野战弹药油料补给中心',
  effects: ['集团军补给消耗降低 20%', '偏远省份作战断粮耐受天数 +5 天'],
  stats: { '补给节约': '+20%', '补给吞吐': '+50%' },
 },

 // ================= 3. 炮兵与火力压制 (ARTILLERY) =================
 // Row 0: 牵引式野战榴弹炮
 {
  id: 'art_howitzer_1',
  name: '轻型野战榴弹炮',
  branch: 'artillery',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'artillery',
  artKey: 'howitzer_light',
  baseDays: 105,
  summary: '配备 75mm/105mm 牵引式轻型榴弹炮，提供主力师级火力伴随',
  effects: ['软目标杀伤 +25%', '防御炮击压制 +20%'],
  stats: { '软杀伤': '+25', '射程': '11km', '破片杀伤': '+20%' },
 },
 {
  id: 'art_howitzer_2',
  name: '中口径加榴火炮',
  branch: 'artillery',
  tier: 2,
  col: 1,
  row: 0,
  year: 1939,
  icon: 'artillery',
  artKey: 'howitzer_light',
  prerequisiteIds: ['art_howitzer_1'],
  baseDays: 145,
  summary: '换装 122mm/150mm 长身管加农榴弹炮，射程与弹片威力剧增',
  effects: ['软目标杀伤 +35%', '战壕攻坚破障 +25%'],
  stats: { '软杀伤': '+40', '射程': '16km', '要塞压制': '+25%' },
 },
 {
  id: 'art_howitzer_3',
  name: '重型远程攻坚重炮',
  branch: 'artillery',
  tier: 3,
  col: 2,
  row: 0,
  year: 1942,
  icon: 'artillery',
  artKey: 'howitzer_heavy',
  prerequisiteIds: ['art_howitzer_2'],
  baseDays: 185,
  summary: '装备 152mm/203mm 巨型加农炮，发射千磅高爆弹粉碎一切防御',
  effects: ['软目标杀伤 +50%', '要塞掩体毁伤 +45%', '大兵团交战压制 +40%'],
  stats: { '软杀伤': '+65', '射程': '24km', '工事摧毁': '+45%' },
 },
 {
  id: 'art_howitzer_4',
  name: '现代化火箭增程加榴炮',
  branch: 'artillery',
  tier: 4,
  col: 3,
  row: 0,
  year: 1945,
  icon: 'artillery',
  artKey: 'howitzer_heavy',
  prerequisiteIds: ['art_howitzer_3'],
  baseDays: 220,
  summary: '采用底排火箭增程弹与数字化弹道解算器，极限射程突破 35 公里',
  effects: ['超远程跨省份纵深打击', '集团军炮兵火力倍增 +60%'],
  stats: { '软杀伤': '+85', '射程': '35km', '全天候火控': '+50%' },
 },

 // Row 1: 反坦克加农炮
 {
  id: 'art_at_1',
  name: '早期轻型反坦克炮',
  branch: 'artillery',
  tier: 1,
  col: 0,
  row: 1,
  year: 1936,
  icon: 'target',
  artKey: 'at_gun_light',
  baseDays: 100,
  summary: '配备 37mm/45mm 高初速反坦克炮，击穿早期轻型装甲车体',
  effects: ['硬目标杀伤 +20%', '步兵师穿甲深度 +20'],
  stats: { '硬杀伤': '+20', '穿甲深度': '45mm' },
 },
 {
  id: 'art_at_2',
  name: '50/57mm反坦克炮',
  branch: 'artillery',
  tier: 2,
  col: 1,
  row: 1,
  year: 1939,
  icon: 'target',
  artKey: 'at_gun_light',
  prerequisiteIds: ['art_at_1'],
  baseDays: 140,
  summary: '采用钨芯穿甲弹与长身管加农设计，正面对抗中型坦克',
  effects: ['硬目标杀伤 +35%', '穿甲深度 +45'],
  stats: { '硬杀伤': '+40', '穿甲深度': '95mm' },
 },
 {
  id: 'art_at_3',
  name: '75/88mm重型反坦克炮',
  branch: 'artillery',
  tier: 3,
  col: 2,
  row: 1,
  year: 1942,
  icon: 'target',
  artKey: 'at_gun_light',
  prerequisiteIds: ['art_at_2'],
  baseDays: 180,
  summary: '传奇 71倍径长身管反坦克炮（如 PaK 43 / BS-3），千米之外秒杀重坦',
  effects: ['硬目标杀伤 +55%', '穿甲深度 +80', '对敌坦克心理震慑 +30%'],
  stats: { '硬杀伤': '+70', '穿甲深度': '190mm', '首发摧毁率': '+60%' },
 },
 {
  id: 'art_at_4',
  name: '128mm超重型反坦克炮',
  branch: 'artillery',
  tier: 4,
  col: 3,
  row: 1,
  year: 1944,
  icon: 'target',
  artKey: 'at_gun_light',
  prerequisiteIds: ['art_at_3'],
  baseDays: 215,
  summary: '安装巨型炮口制退器与半自动装填机，毁灭两千米外任何重型装甲目标',
  effects: ['硬目标杀伤 +75%', '穿甲深度 +120'],
  stats: { '硬杀伤': '+95', '穿甲深度': '260mm' },
 },

 // Row 2: 野战防空高射炮与火箭炮
 {
  id: 'art_aa_1',
  name: '轻型机关高射炮',
  branch: 'artillery',
  tier: 1,
  col: 0,
  row: 2,
  year: 1936,
  icon: 'shield',
  artKey: 'aa_gun',
  baseDays: 95,
  summary: '装备 20mm/37mm 高射速机关炮，防御俯冲轰炸与低空袭扰',
  effects: ['防空火力 +20%', '地面部队受近距对地支援机(CAS)轰炸损耗 -30%'],
  stats: { '防空射击': '+20', '低空拦截': '+35%' },
 },
 {
  id: 'art_aa_2',
  name: '大口径高空高射炮',
  branch: 'artillery',
  tier: 2,
  col: 1,
  row: 2,
  year: 1939,
  icon: 'shield',
  artKey: 'aa_gun',
  prerequisiteIds: ['art_aa_1'],
  baseDays: 140,
  summary: '装备 85mm/88mm/90mm 高空高射炮，发射定高引信破片弹摧毁轰炸机编队',
  effects: ['防空火力 +45%', '省份战略防空能力 +50%', '兼具致命反坦克平射能力'],
  stats: { '防空射击': '+50', '射高': '11000m', '平射穿甲': '+60' },
 },
 {
  id: 'art_rocket_1',
  name: '野战多管火箭炮',
  branch: 'artillery',
  tier: 3,
  col: 2,
  row: 2,
  year: 1941,
  icon: 'flame',
  artKey: 'rocket_artillery',
  prerequisiteIds: ['art_howitzer_2'],
  baseDays: 175,
  summary: '火箭滑轨发射车（如喀秋莎/白尾海雕），数秒内倾泻数十枚重型火箭',
  effects: ['软目标杀伤 +60%', '战场士气打击 +50%', '快速机动打了就跑'],
  stats: { '软杀伤': '+75', '齐射火力': '320kg', '心理打击': '+50%' },
 },
 {
  id: 'art_rocket_2',
  name: '重型饱和火箭炮兵群',
  branch: 'artillery',
  tier: 4,
  col: 3,
  row: 2,
  year: 1944,
  icon: 'flame',
  artKey: 'rocket_artillery',
  prerequisiteIds: ['art_rocket_1'],
  baseDays: 210,
  summary: '300mm 巨型重型火箭弹，制造整片森林化为灰烬的毁灭级弹幕',
  effects: ['软目标杀伤 +85%', '敌军阵地组织度瞬间清零 +40%'],
  stats: { '软杀伤': '+110', '毁伤半径': '500m', '阵地破坏': '+80%' },
 },

 // ================= 4. 装甲战车与坦克 (ARMOR) =================
 // Row 0: 轻型巡航坦克
 {
  id: 'arm_light_1',
  name: '基础轻型巡航坦克',
  branch: 'armor',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'tank',
  artKey: 'tank_light',
  baseDays: 110,
  summary: '装备 37mm 炮与薄装甲的机动侦察战车，时速达 50km/h',
  effects: ['突破速度 +40%', '大地图机动穿插 +25%'],
  stats: { '装甲': '25mm', '速度': '52km/h', '突破': '+20' },
 },
 {
  id: 'arm_light_2',
  name: '改进轻型坦克',
  branch: 'armor',
  tier: 2,
  col: 1,
  row: 0,
  year: 1938,
  icon: 'tank',
  artKey: 'tank_light',
  prerequisiteIds: ['arm_light_1'],
  baseDays: 145,
  summary: '加固扭杆悬挂与 45mm 炮塔，兼顾步兵火力支援与侧翼大纵深奔袭',
  effects: ['突破能力 +30%', '装甲可靠性 +20%'],
  stats: { '装甲': '38mm', '速度': '58km/h', '突破': '+30' },
 },
 {
  id: 'arm_amphibious',
  name: '两栖装甲战车',
  branch: 'armor',
  tier: 3,
  col: 2,
  row: 0,
  year: 1941,
  icon: 'tank',
  artKey: 'tank_light',
  prerequisiteIds: ['arm_light_2'],
  baseDays: 175,
  summary: '加装充气浮筒与螺旋桨推进器，直接从登陆艇下海抢滩夺桥',
  effects: ['跨海登陆作战惩罚 -70%', '跨大河进攻加成 +40%'],
  stats: { '抢滩攻坚': '+70%', '水上速度': '10km/h' },
 },

 // Row 1: 中型主战突破坦克 (主力线)
 {
  id: 'arm_medium_1',
  name: '早期中型坦克',
  branch: 'armor',
  tier: 1,
  col: 0,
  row: 1,
  year: 1937,
  icon: 'tank',
  artKey: 'tank_medium',
  baseDays: 130,
  summary: '装备 75mm 短管炮与 40mm 装甲，作为装甲师突破的主力核心',
  effects: ['装甲硬度 +30%', '突破攻击 +35%', '软杀伤 +25%'],
  stats: { '装甲': '50mm', '穿深': '65mm', '突破': '+40' },
 },
 {
  id: 'arm_medium_2',
  name: '改进主力中型坦克',
  branch: 'armor',
  tier: 2,
  col: 1,
  row: 1,
  year: 1939,
  icon: 'tank',
  artKey: 'tank_medium',
  prerequisiteIds: ['arm_medium_1'],
  baseDays: 165,
  summary: '大倾角装甲与长身管高初速主炮（如 T-34/76 / M4谢尔曼 / 四号长管）',
  effects: ['装甲师整体战斗力跃升 +45%', '大兵团战损比大幅降低 +35%'],
  stats: { '装甲': '75mm倾斜', '穿深': '115mm', '突破': '+60' },
  historicalQuote: '倾斜的装甲与咆哮的柴油机，将成为撕裂敌军防线的钢铁重锤。',
 },
 {
  id: 'arm_medium_3',
  name: '先进主战突破坦克',
  branch: 'armor',
  tier: 3,
  col: 2,
  row: 1,
  year: 1941,
  icon: 'tank',
  artKey: 'tank_medium',
  prerequisiteIds: ['arm_medium_2'],
  baseDays: 195,
  summary: '装备 85mm/76mm 增膛压火炮与避弹外形炮塔（如 T-34/85 / 黑豹）',
  effects: ['硬目标杀伤 +55%', '突破能力 +60%', '装甲防御 +50%'],
  stats: { '装甲': '100mm', '穿深': '160mm', '突破': '+80' },
 },
 {
  id: 'arm_medium_4',
  name: '现代化主战坦克(MBT)',
  branch: 'armor',
  tier: 4,
  col: 3,
  row: 1,
  year: 1945,
  icon: 'tank',
  artKey: 'tank_modern',
  prerequisiteIds: ['arm_medium_3', 'arm_heavy_2'],
  baseDays: 230,
  summary: '融合中坦机动与重坦装甲火力（如 百夫长 / T-54 / M48），终结坦克分类',
  effects: ['全地形碾压推进 +70%', '全天候双向稳定行进射击 +60%'],
  stats: { '装甲': '180mm', '穿深': '230mm', '突破': '+110' },
 },

 // Row 2: 重型攻坚突破坦克
 {
  id: 'arm_heavy_1',
  name: '早期重型突破坦克',
  branch: 'armor',
  tier: 2,
  col: 1,
  row: 2,
  year: 1938,
  icon: 'tank',
  artKey: 'tank_heavy',
  prerequisiteIds: ['arm_medium_1'],
  baseDays: 160,
  summary: '拥有 80mm 以上厚重装甲，专职在敌方密集防线上强行撕开缺口（如 KV-1/玛蒂尔达）',
  effects: ['防御免伤率 +40%', '强攻要塞突破 +45%'],
  stats: { '装甲': '90mm', '硬度': '85%', '突破': '+50' },
 },
 {
  id: 'arm_heavy_2',
  name: '重装甲攻坚坦克 II',
  branch: 'armor',
  tier: 3,
  col: 2,
  row: 2,
  year: 1941,
  icon: 'tank',
  artKey: 'tank_heavy',
  prerequisiteIds: ['arm_heavy_1'],
  baseDays: 200,
  summary: '装备 88mm/122mm 巨炮与 120mm 重装甲（如 虎式 / IS-2）',
  effects: ['战场硬杀伤 +70%', '无视中小口径反坦克炮射击 +60%'],
  stats: { '装甲': '120-150mm', '穿深': '195mm', '突破': '+90' },
 },
 {
  id: 'arm_heavy_3',
  name: '超重型钢铁要塞',
  branch: 'armor',
  tier: 4,
  col: 3,
  row: 2,
  year: 1944,
  icon: 'tank',
  artKey: 'tank_heavy',
  prerequisiteIds: ['arm_heavy_2'],
  baseDays: 235,
  summary: '百吨级陆地巡洋舰（如 鼠式/T95/IS-7），安装 130/150mm 舰炮级主炮',
  effects: ['正面绝对不可穿透防御 +80%', '城市要塞完全夷为平地 +75%'],
  stats: { '装甲': '220mm', '穿深': '280mm', '战场威慑': '+100' },
 },

 // Row 3: 坦克歼击车与突击炮
 {
  id: 'arm_td_1',
  name: '突击炮攻坚车',
  branch: 'armor',
  tier: 2,
  col: 1,
  row: 3,
  year: 1939,
  icon: 'target',
  artKey: 'tank_destroyer',
  prerequisiteIds: ['arm_medium_1'],
  baseDays: 140,
  summary: '取消旋转炮塔，直接在底盘安装 75mm 加农炮，造价低廉火力充沛（如 三号突击炮）',
  effects: ['装甲装备制造成本降低 25%', '防御伏击加成 +35%'],
  stats: { '穿深': '110mm', '成本节省': '-25%' },
 },
 {
  id: 'arm_td_2',
  name: '重型长身管坦克歼击车',
  branch: 'armor',
  tier: 3,
  col: 2,
  row: 3,
  year: 1942,
  icon: 'target',
  artKey: 'tank_destroyer',
  prerequisiteIds: ['arm_td_1', 'arm_medium_2'],
  baseDays: 185,
  summary: '在中/重坦底盘安装 88mm/100mm 强力加农炮（如 猎豹 / SU-100 / 斐迪南）',
  effects: ['硬目标杀伤 +70%', '两千米超视距猎杀坦克 +50%'],
  stats: { '穿深': '210mm', '硬杀伤': '+85', '伏击加成': '+50%' },
 },
 {
  id: 'arm_sp_artillery',
  name: '大口径自行野战火炮',
  branch: 'armor',
  tier: 3,
  col: 2,
  row: 4,
  year: 1941,
  icon: 'flame',
  artKey: 'sp_artillery',
  prerequisiteIds: ['arm_medium_2', 'art_howitzer_2'],
  baseDays: 180,
  summary: '在履带底盘安装 150mm/152mm 重型榴弹炮（如 蟋蟀/牧师/SU-152），伴随装甲集群直瞄/曲射',
  effects: ['伴随坦克进攻软杀伤 +60%', '行进间快速开火展开 +40%'],
  stats: { '软杀伤': '+75', '装甲伴随': '+50%' },
 },

 // ================= 5. 国家工业与产能 (INDUSTRY) =================
 // Row 0: 基础母机与精密切削
 {
  id: 'ind_machine_tools_1',
  name: '基础工业工作母机',
  branch: 'industry',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'tool',
  artKey: 'machine_tools',
  baseDays: 100,
  summary: '普及高刚性金属切削机床与冲压模具，打下军工产能基石',
  effects: ['军工厂最高生产效率上限 +10%', '全国军工总产能 +10%'],
  stats: { '生产效率上限': '+10%', '军工产能': '+10%' },
 },
 {
  id: 'ind_machine_tools_2',
  name: '改进精密切削机床',
  branch: 'industry',
  tier: 2,
  col: 1,
  row: 0,
  year: 1938,
  icon: 'tool',
  artKey: 'machine_tools',
  prerequisiteIds: ['ind_machine_tools_1'],
  baseDays: 140,
  summary: '引入数显微米级铣床与精密齿轮滚齿机，军械零件具备高度互换性',
  effects: ['军工厂生产效率增长速度 +15%', '全国军工产能 +10%'],
  stats: { '效率增长': '+15%', '军工产能': '+10%' },
 },
 {
  id: 'ind_machine_tools_3',
  name: '先进自动化机床集群',
  branch: 'industry',
  tier: 3,
  col: 2,
  row: 0,
  year: 1941,
  icon: 'tool',
  artKey: 'machine_tools',
  prerequisiteIds: ['ind_machine_tools_2'],
  baseDays: 180,
  summary: '采用液压仿形车床与专用组合机床，实现大批量枪炮自动化加工',
  effects: ['军工生产效率上限 +15%', '武器换装生产线惩罚降低 30%'],
  stats: { '效率上限': '+15%', '换线保留': '+30%' },
 },
 {
  id: 'ind_machine_tools_4',
  name: '现代化工业制造体系',
  branch: 'industry',
  tier: 4,
  col: 3,
  row: 0,
  year: 1944,
  icon: 'tool',
  artKey: 'machine_tools',
  prerequisiteIds: ['ind_machine_tools_3'],
  baseDays: 220,
  summary: '数控化预研与超大型万吨水压锻造机，制造航母龙骨与巨型坦克一体装甲',
  effects: ['全国重工业总产值 +25%', '大型装备制造工期缩短 20%'],
  stats: { '总产能': '+25%', '工期缩短': '-20%' },
 },

 // Row 1: 集中式生产工业 (集中产能路线)
 {
  id: 'ind_concentrated_1',
  name: '集中式流水线 I',
  branch: 'industry',
  tier: 1,
  col: 0,
  row: 1,
  year: 1936,
  icon: 'factory',
  artKey: 'assembly_line',
  baseDays: 105,
  summary: '在核心工业省份建立超大型集中制造基地与标准福特制流水线',
  effects: ['民用工厂建造速度 +10%', '军工厂产出效率 +10%', '省份可建工厂上限 +20%'],
  stats: { '民用建造': '+10%', '军工产出': '+10%', '建筑槽位': '+20%' },
 },
 {
  id: 'ind_concentrated_2',
  name: '集中式流水线 II',
  branch: 'industry',
  tier: 2,
  col: 1,
  row: 1,
  year: 1939,
  icon: 'factory',
  artKey: 'assembly_line',
  prerequisiteIds: ['ind_concentrated_1'],
  baseDays: 150,
  summary: '扩建巨型钢铁铸造与汽车/坦克超级装配联合体',
  effects: ['军工厂产出效率 +15%', '省份工业槽位上限 +20%'],
  stats: { '军工产出': '+15%', '建筑槽位': '+20%' },
 },
 {
  id: 'ind_concentrated_3',
  name: '集中式装配中心 III',
  branch: 'industry',
  tier: 3,
  col: 2,
  row: 1,
  year: 1942,
  icon: 'factory',
  artKey: 'assembly_line',
  prerequisiteIds: ['ind_concentrated_2'],
  baseDays: 190,
  summary: '24小时三班倒无停歇超级工厂，以庞大体量压垮敌国',
  effects: ['军工厂产出效率 +20%', '工业总产能 +15%'],
  stats: { '军工产出': '+20%', '工业总量': '+15%' },
 },

 // Row 2: 建筑工程学与地下设施
 {
  id: 'ind_construction_1',
  name: '基础建筑工程学',
  branch: 'industry',
  tier: 1,
  col: 0,
  row: 2,
  year: 1936,
  icon: 'building',
  artKey: 'assembly_line',
  baseDays: 95,
  summary: '标配蒸汽挖掘机、水泥预拌站与轨道运输，加速国家基础设施建造',
  effects: ['民用工厂建造速度 +10%', '基础设施与铁路建造速度 +15%'],
  stats: { '建造速度': '+10%', '基建效率': '+15%' },
 },
 {
  id: 'ind_construction_2',
  name: '强化混凝土工程',
  branch: 'industry',
  tier: 2,
  col: 1,
  row: 2,
  year: 1939,
  icon: 'building',
  artKey: 'assembly_line',
  prerequisiteIds: ['ind_construction_1'],
  baseDays: 140,
  summary: '采用预应力钢筋混凝土与模块化筑垒技术，速建永备要塞与地下掩体',
  effects: ['省份要塞与海防工事建造速度 +25%', '民用工厂建造速度 +10%'],
  stats: { '要塞建造': '+25%', '建造速度': '+10%' },
 },
 {
  id: 'ind_construction_3',
  name: '全地下防空设防设施',
  branch: 'industry',
  tier: 3,
  col: 2,
  row: 2,
  year: 1942,
  icon: 'shield',
  artKey: 'assembly_line',
  prerequisiteIds: ['ind_construction_2'],
  baseDays: 185,
  summary: '将关键军工流水线搬迁至山体地下岩洞，免疫敌方战略轰炸',
  effects: ['战略轰炸损伤抵消 -60%', '地下工厂防空效能 +40%'],
  stats: { '抗轰炸': '+60%', '工厂受损': '-50%' },
 },

 // Row 3: 合成油与特种冶金
 {
  id: 'ind_synthetic_fuel_1',
  name: '费托法煤炭合成油',
  branch: 'industry',
  tier: 2,
  col: 1,
  row: 3,
  year: 1937,
  icon: 'flame',
  artKey: 'synthetic_fuel',
  baseDays: 145,
  summary: '利用丰富煤炭储量通过催化重整液化合成汽油与柴油，摆脱石油禁运',
  effects: ['解锁【合成炼油厂】建筑', '每座炼油厂每日产出 +20 桶战略燃料'],
  stats: { '合成燃料': '+20/厂', '能源自给': '+30%' },
 },
 {
  id: 'ind_synthetic_rubber',
  name: '丁苯合成橡胶工业',
  branch: 'industry',
  tier: 3,
  col: 2,
  row: 3,
  year: 1940,
  icon: 'tool',
  artKey: 'synthetic_fuel',
  prerequisiteIds: ['ind_synthetic_fuel_1'],
  baseDays: 175,
  summary: '利用石油裂解副产物合成橡胶，保障卡车轮胎与战机自封油箱供应',
  effects: ['全国航空战机与卡车制造成本降低 15%', '战略橡胶储量充沛'],
  stats: { '航空降本': '-15%', '橡胶产出': '+15/厂' },
 },
 {
  id: 'ind_alloy_steel',
  name: '特种镍铬装甲合金钢',
  branch: 'industry',
  tier: 3,
  col: 2,
  row: 4,
  year: 1941,
  icon: 'shield',
  artKey: 'alloy_smelter',
  prerequisiteIds: ['ind_machine_tools_2'],
  baseDays: 180,
  summary: '掌握真空脱气与镍钼合金热处理，制造抗弹力提升 30% 的表面硬化装甲钢',
  effects: ['坦克与主力舰装甲厚度等效 +25%', '穿甲弹芯硬度 +20%'],
  stats: { '装甲等效': '+25%', '防弹力': '+30%' },
 },

 // ================= 6. 航空战机与空优 (AIR) =================
 // Row 0: 活塞式战斗机 (空优线)
 {
  id: 'air_fighter_early',
  name: '早期轻型战斗机',
  branch: 'air',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'fighter',
  artKey: 'fighter_early',
  baseDays: 105,
  summary: '下单翼全金属轻型战斗机，装备双联装航空机枪与封闭座舱',
  effects: ['基础空优争夺力 +20%', '拦截敌机效率 +15%'],
  stats: { '空战制空': '+20', '时速': '480km/h', '机动性': '+35' },
 },
 {
  id: 'air_fighter_improved',
  name: '改进主力空优战斗机',
  branch: 'air',
  tier: 2,
  col: 1,
  row: 0,
  year: 1938,
  icon: 'fighter',
  artKey: 'fighter_early',
  prerequisiteIds: ['air_fighter_early'],
  baseDays: 145,
  summary: '装备 1000 马力液冷/星型发动机与 20mm 航炮（如 Bf 109E / 喷火 / 零战）',
  effects: ['空中优势争夺战力 +40%', '敌轰炸机击坠率 +35%'],
  stats: { '空战制空': '+45', '时速': '570km/h', '航炮火力': '+40' },
  historicalQuote: '空中的猎手在万米高空呼啸，云层之上的胜利将决定大地的归属。',
 },
 {
  id: 'air_fighter_advanced',
  name: '先进远程空优战机',
  branch: 'air',
  tier: 3,
  col: 2,
  row: 0,
  year: 1941,
  icon: 'fighter',
  artKey: 'fighter_advanced',
  prerequisiteIds: ['air_fighter_improved'],
  baseDays: 185,
  summary: '大容量副油箱、水滴座舱与层流翼（如 P-51D野马 / 喷火后期 / 雅克-3）',
  effects: ['空优争夺战力 +60%', '护航半径增加 150%', '高空机动性 +40%'],
  stats: { '空战制空': '+70', '作战半径': '1200km', '时速': '710km/h' },
 },
 {
  id: 'air_fighter_late',
  name: '后期活塞终极空优机',
  branch: 'air',
  tier: 4,
  col: 3,
  row: 0,
  year: 1944,
  icon: 'fighter',
  artKey: 'fighter_advanced',
  prerequisiteIds: ['air_fighter_advanced'],
  baseDays: 215,
  summary: '2000 马力涡轮增压发动机与 30mm 大口径航炮（如 暴风 / 烈风 / Ta 152）',
  effects: ['空优战力 +80%', '重型轰炸机瞬间解体击坠率 +60%'],
  stats: { '空战制空': '+95', '时速': '760km/h', '秒伤投射': '8.5kg/s' },
 },
 {
  id: 'air_fighter_jet',
  name: '后掠翼喷气式战斗机',
  branch: 'air',
  tier: 5,
  col: 4,
  row: 0,
  year: 1945,
  icon: 'fighter',
  artKey: 'fighter_jet',
  prerequisiteIds: ['air_fighter_late'],
  baseDays: 250,
  summary: '轴流式喷气涡轮发动机与后掠翼（如 Me 262 / F-86 / 米格-15），划时代速度革命',
  effects: ['绝对制空碾压活塞战机 +120%', '飞行时速突破 950km/h', '无法被地面普通防空炮锁定'],
  stats: { '空战制空': '+150', '时速': '960km/h', '代差碾压': '+100%' },
 },

 // Row 1: 近距离对地支援机 (CAS)
 {
  id: 'air_cas_1',
  name: '早期俯冲支援轰炸机',
  branch: 'air',
  tier: 1,
  col: 0,
  row: 1,
  year: 1936,
  icon: 'target',
  artKey: 'fighter_cas',
  baseDays: 100,
  summary: '装备俯冲减速板与航弹挂架，专精对敌前沿阵地进行点穴式精确轰炸（如 斯图卡/SBD）',
  effects: ['陆军交战近距空中支援杀伤 +30%', '摧毁敌军装甲先头部队'],
  stats: { '对地杀伤': '+30', '俯冲精度': '85%' },
 },
 {
  id: 'air_cas_2',
  name: '重装甲强击支援机',
  branch: 'air',
  tier: 2,
  col: 1,
  row: 1,
  year: 1939,
  icon: 'target',
  artKey: 'fighter_cas',
  prerequisiteIds: ['air_cas_1'],
  baseDays: 145,
  summary: '全装甲澡盆座舱、37mm 反坦克航炮与航空火箭弹（如 伊尔-2 黑色死神 / 飓风对地型）',
  effects: ['对敌坦克集群毁伤 +50%', '地面部队受 CAS 掩护突破 +35%'],
  stats: { '对地杀伤': '+55', '破甲航炮': '37mm', '生存性': '+60%' },
 },
 {
  id: 'air_cas_3',
  name: '先进空地对地攻击机',
  branch: 'air',
  tier: 3,
  col: 2,
  row: 1,
  year: 1942,
  icon: 'target',
  artKey: 'fighter_cas',
  prerequisiteIds: ['air_cas_2'],
  baseDays: 185,
  summary: '挂载 8 枚无控对地火箭与 1000 磅重型航弹，彻底清除敌方堑壕要塞',
  effects: ['地面阵地瓦解率 +70%', '敌军组织度崩溃加速 +45%'],
  stats: { '对地杀伤': '+80', '弹药投送': '1500kg' },
 },

 // Row 2: 战术与战略轰炸机
 {
  id: 'air_bomber_tactical',
  name: '双发战术轰炸机',
  branch: 'air',
  tier: 1,
  col: 0,
  row: 2,
  year: 1937,
  icon: 'plane',
  artKey: 'bomber_strat',
  baseDays: 120,
  summary: '双发中程水平轰炸机（如 He 111 / B-25 / 图-2），兼顾前线支援与纵深铁路破坏',
  effects: ['敌军后方补给线破坏 +35%', '机场与火车站瘫痪打击 +30%'],
  stats: { '战术轰炸': '+40', '载弹量': '2000kg' },
 },
 {
  id: 'air_bomber_strategic_1',
  name: '四发重型战略轰炸机',
  branch: 'air',
  tier: 2,
  col: 1,
  row: 2,
  year: 1940,
  icon: 'plane',
  artKey: 'bomber_strat',
  prerequisiteIds: ['air_bomber_tactical'],
  baseDays: 175,
  summary: '四发重型空中堡垒（如 B-17 / 兰开斯特），万米高空投掷万磅炸弹摧毁敌国工业',
  effects: ['敌国工业省份摧毁效率 +60%', '战略轰炸摧毁工厂与基建'],
  stats: { '战略轰炸': '+75', '载弹量': '6000kg', '航程': '3000km' },
 },
 {
  id: 'air_bomber_strategic_2',
  name: '超远程超级战略轰炸机',
  branch: 'air',
  tier: 3,
  col: 2,
  row: 2,
  year: 1943,
  icon: 'plane',
  artKey: 'bomber_strat',
  prerequisiteIds: ['air_bomber_strategic_1'],
  baseDays: 215,
  summary: '全加压座舱与遥控自卫炮塔（如 B-29 超级空中堡垒），具备洲际打击与运载核武能力',
  effects: ['敌国全境工业瘫痪打击 +90%', '解锁【终极战略投送载具】资格'],
  stats: { '战略轰炸': '+110', '载弹量': '9000kg', '航程': '5500km' },
 },

 // ================= 7. 海军舰艇与远洋 (NAVAL) =================
 // Row 0: 水下狼群潜艇
 {
  id: 'nav_sub_1',
  name: '早期近海柴电潜艇',
  branch: 'naval',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'anchor',
  artKey: 'submarine_ocean',
  baseDays: 100,
  summary: '配备 4 具艇艏鱼雷管与甲板炮，在沿海航线上猎杀商船与轻型护卫舰',
  effects: ['敌国海上运输线破交效率 +25%', '潜航隐匿性 +20%'],
  stats: { '鱼雷杀伤': '+30', '隐蔽度': '85' },
 },
 {
  id: 'nav_sub_2',
  name: '远洋破交狼群潜艇',
  branch: 'naval',
  tier: 2,
  col: 1,
  row: 0,
  year: 1939,
  icon: 'anchor',
  artKey: 'submarine_ocean',
  prerequisiteIds: ['nav_sub_1'],
  baseDays: 145,
  summary: 'VII型远洋潜艇，配备通气管与无线电协同，在大洋深处绞杀敌方补给船队',
  effects: ['远洋商船护航击沉率 +50%', '敌国战略资源进口阻绝率 +40%'],
  stats: { '鱼雷杀伤': '+55', '航程': '8000海里', '狼群加成': '+40%' },
 },
 {
  id: 'nav_sub_3',
  name: '先进流线型水下潜艇',
  branch: 'naval',
  tier: 3,
  col: 2,
  row: 0,
  year: 1943,
  icon: 'anchor',
  artKey: 'submarine_ocean',
  prerequisiteIds: ['nav_sub_2'],
  baseDays: 190,
  summary: 'XXI型大容量蓄电池水下高速潜艇，配备液压快装鱼雷与声纳诱饵',
  effects: ['水下航速超越护航驱逐舰', '反潜声纳探测发现率降低 60%'],
  stats: { '水下时速': '18节', '隐蔽度': '95', '突防率': '+70%' },
 },

 // Row 1: 水面护航与主力驱巡
 {
  id: 'nav_dd_1',
  name: '舰队护航驱逐舰',
  branch: 'naval',
  tier: 1,
  col: 0,
  row: 1,
  year: 1936,
  icon: 'warship',
  artKey: 'destroyer',
  baseDays: 105,
  summary: '装备 127mm 高平两用炮、深水炸弹滑轨与声纳，主力舰队护航尖兵',
  effects: ['舰队反潜探测能力 +35%', '鱼雷齐射反击能力 +30%'],
  stats: { '反潜火力': '+35', '航速': '36节' },
 },
 {
  id: 'nav_cl_1',
  name: '条约型轻/重巡洋舰',
  branch: 'naval',
  tier: 2,
  col: 1,
  row: 1,
  year: 1938,
  icon: 'warship',
  artKey: 'destroyer',
  prerequisiteIds: ['nav_dd_1'],
  baseDays: 155,
  summary: '装备 152mm/203mm 主炮与高强度侧舷装甲，承担舰队防空遮蔽与巡洋作战',
  effects: ['舰队防空火力屏障 +50%', '夜战水面突击战力 +40%'],
  stats: { '水面炮战': '+50', '防空掩护': '+50%' },
 },
 {
  id: 'nav_bb_1',
  name: '超无畏级大口径战列舰',
  branch: 'naval',
  tier: 3,
  col: 2,
  row: 1,
  year: 1940,
  icon: 'warship',
  artKey: 'battleship',
  prerequisiteIds: ['nav_cl_1'],
  baseDays: 200,
  summary: '406mm/460mm 巨型主炮与 300mm 装甲带，大舰巨炮时代的终极海权象征',
  effects: ['水面决战主力炮战杀伤 +80%', '对沿海省份进行毁灭性舰炮轰击'],
  stats: { '主炮口径': '406mm', '装甲厚度': '350mm', '岸轰威力': '+100' },
 },

 // Row 2: 舰队重装甲航空母舰 (海战航母路线)
 {
  id: 'nav_carrier_1',
  name: '条约舰队航空母舰',
  branch: 'naval',
  tier: 2,
  col: 1,
  row: 2,
  year: 1937,
  icon: 'anchor',
  artKey: 'carrier',
  prerequisiteIds: ['nav_dd_1'],
  baseDays: 165,
  summary: '改装/新建全通飞行甲板，搭载 50 架舰载俯冲轰炸机与战斗机',
  effects: ['超视距 150 公里海空打击', '争夺制海权制空权'],
  stats: { '机库容量': '55架', '海空打击': '+40' },
 },
 {
  id: 'nav_carrier_2',
  name: '重型装甲舰队航母',
  branch: 'naval',
  tier: 3,
  col: 2,
  row: 2,
  year: 1941,
  icon: 'anchor',
  artKey: 'carrier',
  prerequisiteIds: ['nav_carrier_1'],
  baseDays: 210,
  summary: '装甲飞行甲板、双层机库与弹射起飞系统，搭载 85 架以上精锐舰载机（如 埃塞克斯级）',
  effects: ['超视距 300 公里毁灭级海空打击', '彻底终结战列舰海权时代 +70%'],
  stats: { '机库容量': '90架', '打击半径': '350km', '海区制空': '+80%' },
 },

 // ================= 8. 电子雷达与工程 (ELECTRONICS) =================
 // Row 0: 计算科学与密码战
 {
  id: 'elec_diff_engine',
  name: '机械式差分计算机',
  branch: 'electronics',
  tier: 1,
  col: 0,
  row: 0,
  year: 1936,
  icon: 'cpu',
  artKey: 'diff_engine',
  baseDays: 95,
  summary: '利用精密多轴联动齿轮与打孔卡片，快速计算炮兵射表与弹道偏航',
  effects: ['全国科技基础研发速度 +4%', '炮兵首发命中率 +10%'],
  stats: { '全科技科研速度': '+4%', '弹道解算': '+10%', '工业计算': '+5%' },
  historicalQuote: '齿轮旋转之间，人类首次将纯粹的数学逻辑具象为改写战局的力量。',
 },
 {
  id: 'elec_vacuum_tube',
  name: '大型电子管计算机',
  branch: 'electronics',
  tier: 2,
  col: 1,
  row: 0,
  year: 1939,
  icon: 'cpu',
  artKey: 'diff_engine',
  prerequisiteIds: ['elec_diff_engine'],
  baseDays: 145,
  summary: '采用数千只真空三极电子管替代机械轴，运算速度提升千倍（如 ENIAC）',
  effects: ['全国科技基础研发速度 +7%', '生产排产资源损耗 -10%', '自动解锁第4科研槽位'],
  stats: { '全科技科研速度': '+7%', '计算速度': '5000op/s', '换装效率': '+10%' },
 },
 {
  id: 'elec_enigma_crypto',
  name: '机电密码破译阵列',
  branch: 'electronics',
  tier: 3,
  col: 2,
  row: 0,
  year: 1941,
  icon: 'radio',
  artKey: 'diff_engine',
  prerequisiteIds: ['elec_vacuum_tube'],
  baseDays: 185,
  summary: '组建布莱切利园级密码破译机，全面截获并还原敌军最高统帅部密电',
  effects: ['破解敌国全部战场战术意图 +30%', '空战与海战预警时间提前 40%', '间谍防护 +35%'],
  stats: { '密码破译': '+30%', '战前预警': '+40%', '情报获取': '+35%' },
 },
 {
  id: 'elec_digital_comp',
  name: '存储程序通用数字机',
  branch: 'electronics',
  tier: 4,
  col: 3,
  row: 0,
  year: 1944,
  icon: 'cpu',
  artKey: 'diff_engine',
  prerequisiteIds: ['elec_enigma_crypto'],
  baseDays: 220,
  summary: '冯·诺依曼架构通用计算机，实现弹道轨迹、流体力学与核裂变内爆全数字模拟',
  effects: ['全国科技研发速度 +10%', '解锁核工程计算支持'],
  stats: { '全科技科研速度': '+10%', '复杂物理模拟': '+100%' },
 },

 // Row 1: 无线电与雷达相控阵网
 {
  id: 'elec_radio_1',
  name: '甚高频军用步谈机',
  branch: 'electronics',
  tier: 1,
  col: 0,
  row: 1,
  year: 1936,
  icon: 'radio',
  artKey: 'radar_array',
  baseDays: 90,
  summary: '为坦克车长与步兵连部配发战术无线电台，彻底消除旗语通讯延迟',
  effects: ['全军增援进入战场速度 +25%', '步坦协同进攻混乱率 -30%'],
  stats: { '增援速率': '+25%', '协调效率': '+30%', '通讯半径': '25km' },
 },
 {
  id: 'elec_radar_decimeter',
  name: '分米波预警雷达网',
  branch: 'electronics',
  tier: 2,
  col: 1,
  row: 1,
  year: 1939,
  icon: 'radio',
  artKey: 'radar_array',
  prerequisiteIds: ['elec_radio_1'],
  baseDays: 145,
  summary: '沿海岸线与边境部署巨型雷达天线塔，探测 160 公里外敌方机群',
  effects: ['省份雷达建筑解锁（分米波段）', '本土防空截击战力 +30%', '夜间海面搜舰 +20%'],
  stats: { '雷达探测': '160km', '防空截击': '+30%', '夜战视野': '+20%' },
 },
 {
  id: 'elec_radar_centimeter',
  name: '厘米波多腔磁控管',
  branch: 'electronics',
  tier: 3,
  col: 2,
  row: 1,
  year: 1942,
  icon: 'radio',
  artKey: 'radar_array',
  prerequisiteIds: ['elec_radar_decimeter'],
  baseDays: 190,
  summary: '高频厘米波雷达可小型化安装在战机机头与巡逻机上，精确捕捉潜艇通气管',
  effects: ['省份雷达建筑升级为厘米波段', '潜艇搜索发现率 +50%', '舰炮雷达火控命中率 +35%'],
  stats: { '雷达探测': '300km', '反潜搜索': '+50%', '舰炮火控': '+35%' },
 },
 {
  id: 'elec_radar_firecontrol',
  name: '厘米波机载/舰载火控雷达',
  branch: 'electronics',
  tier: 4,
  col: 3,
  row: 1,
  year: 1944,
  icon: 'radio',
  artKey: 'radar_array',
  prerequisiteIds: ['elec_radar_centimeter'],
  baseDays: 220,
  summary: '自动跟踪盲降与夜间火控雷达，实现全天候无视烟雾与黑夜的高精度齐射',
  effects: ['全天候炮击与空战命中率 +40%', '反导与防空效率倍增 +50%'],
  stats: { '火控精度': '+40%', '全天候作战': '+50%' },
 },

 // Row 2: 核工程与终极威慑
 {
  id: 'elec_atomic_theory',
  name: '重核裂变与反应堆',
  branch: 'electronics',
  tier: 3,
  col: 2,
  row: 2,
  year: 1941,
  icon: 'zap',
  artKey: 'atomic_reactor',
  prerequisiteIds: ['elec_vacuum_tube'],
  baseDays: 220,
  summary: '证实铀-235 链式裂变中子倍增原理，在地下建造重水石墨反应堆',
  effects: ['国家战略威慑指数 +50', '科技前沿总览解锁【曼哈顿工程级重工业】'],
  stats: { '战略威慑': '+50', '研究突破': '+15%', '核能储备': '+10' },
 },
 {
  id: 'elec_atomic_isotope',
  name: '电磁同位素气体分离',
  branch: 'electronics',
  tier: 4,
  col: 3,
  row: 2,
  year: 1943,
  icon: 'zap',
  artKey: 'atomic_reactor',
  prerequisiteIds: ['elec_atomic_theory'],
  baseDays: 240,
  summary: '建造千级回旋加速器与气体扩散分离塔，提纯武器级高浓缩铀与钚-239',
  effects: ['战略威慑指数 +80', '裂变材料生产产率 +100%'],
  stats: { '战略威慑': '+80', '高浓缩物料': '+100%' },
 },
 {
  id: 'elec_atomic_weapon',
  name: '内爆式核裂变装置',
  branch: 'electronics',
  tier: 5,
  col: 4,
  row: 2,
  year: 1945,
  icon: 'zap',
  artKey: 'atomic_reactor',
  prerequisiteIds: ['elec_atomic_isotope', 'elec_digital_comp'],
  baseDays: 280,
  summary: '完成精准同步内爆透镜引爆，制造改写人类战争历史的终极战略武器',
  effects: ['国家战略绝对威慑 +300', '拥有核打击与核止战终极战略手段'],
  stats: { '战略威慑': '+300', '终极战略武器': '已就绪' },
 },
];

export const TECH_MAP = new Map<string, ResearchTechItem>(
 ALL_RESEARCH_TECHS.map((t) => [t.id, t])
);

// 获取一个国家的科研槽位数量（默认3个，可扩展至4个、5个）
export function getMaxResearchSlots(nation: Nation | null): number {
 if (!nation) return 3;
 if (nation.unlockedResearchSlots && nation.unlockedResearchSlots >= 3) {
  return nation.unlockedResearchSlots;
 }
 // 如果已研发了电子管大型计算机，则自动解锁第4槽位
 const researched = nation.researchedTechIds || [];
 if (researched.includes('elec_vacuum_tube')) return 4;
 return 3;
}

// 计算科技研发加速加成 (来自政令、已研发计算机科技等)
export function getNationalResearchSpeedBonus(nation: Nation | null): {
 totalMultiplier: number;
 percentageBonus: number;
 breakdown: { label: string; bonus: number }[];
} {
 const breakdown: { label: string; bonus: number }[] = [];
 let bonusPercent = 0;

 if (!nation) {
  return { totalMultiplier: 1.0, percentageBonus: 0, breakdown: [] };
 }

 const researched = nation.researchedTechIds || [];

 if (researched.includes('elec_diff_engine')) {
  bonusPercent += 4;
  breakdown.push({ label: '机械差分计算机', bonus: 4 });
 }
 if (researched.includes('elec_vacuum_tube')) {
  bonusPercent += 7;
  breakdown.push({ label: '电子管大型计算机', bonus: 7 });
 }
 if (researched.includes('elec_digital_comp')) {
  bonusPercent += 10;
  breakdown.push({ label: '通用数字计算机', bonus: 10 });
 }

 // Active decrees may directly accelerate the national research program.
 const activeDecreeIds = Array.isArray(nation.activeDecreeIds) ? nation.activeDecreeIds : DEFAULT_ACTIVE_DECREE_IDS;
 activeDecreeIds.forEach((decreeId) => {
  const decree = PRESET_DECREES.find((item) => item.id === decreeId);
  const bonus = decree?.effects.researchSpeedBonus || 0;
  if (bonus) {
   const percentage = Math.round(bonus * 100);
   bonusPercent += percentage;
   breakdown.push({ label: decree!.name, bonus: percentage });
  }
 });

 // 科技理性主义意识形态加成
 if (nation.ideology === '科技理性主义') {
  bonusPercent += 10;
  breakdown.push({ label: '科技理性主义国策', bonus: 10 });
 }

 return {
  totalMultiplier: 1 + bonusPercent / 100,
  percentageBonus: bonusPercent,
  breakdown,
 };
}

// 判定某科技当前是否可研发 (前置科技是否全部满足且自身未研发)
export function canResearchTech(
 tech: ResearchTechItem,
 researchedTechIds: string[],
 activeProjects: ActiveResearchProject[]
): {
 canResearch: boolean;
 isResearched: boolean;
 isResearching: boolean;
 missingPrereqNames: string[];
} {
 const isResearched = researchedTechIds.includes(tech.id);
 const isResearching = activeProjects.some((p) => p.techId === tech.id);

 if (isResearched || isResearching) {
  return {
   canResearch: false,
   isResearched,
   isResearching,
   missingPrereqNames: [],
  };
 }

 const missingPrereqs: string[] = [];
 if (tech.prerequisiteIds && tech.prerequisiteIds.length > 0) {
  for (const prereqId of tech.prerequisiteIds) {
   if (!researchedTechIds.includes(prereqId)) {
    const prereqItem = TECH_MAP.get(prereqId);
    missingPrereqs.push(prereqItem ? prereqItem.name : prereqId);
   }
  }
 }

 return {
  canResearch: missingPrereqs.length === 0,
  isResearched: false,
  isResearching: false,
  missingPrereqNames: missingPrereqs,
 };
}
